### ISSUE TITLE
[runtimes] Animation change mixing problem (unnecessary motion between two similar poses)

### ISSUE THREAD

**Issue by snake5** [EsotericSoftware/spine-runtimes#899] opened 2017-05-11 08:26 UTC
When I change an animation with mixing, the expected behavior is shortest-path interpolation between the two animations. The actual behavior is that additional motion appears between two nearly identical poses.

I am using the spine-c runtime (downloaded early this year).
There are two animation tracks used (body id=0, arm id=1), mix duration is 0.1 (but increasing it didn't help).
Character: [player_char.zip](https://github.com/EsotericSoftware/spine-runtimes/files/992262/player_char.zip)
Animations:  ladder_prepjump, ladder_jump

Recording of the behavior: ![spinebug1crop](https://cloud.githubusercontent.com/assets/1819544/25939045/25a77b36-363a-11e7-8a24-63383df1be0a.gif)
Except the beginning, gif consists of switching between the two animations. There should be almost no motion but the actual result is unwanted, immersion-breaking deformations.

I did some debugging and found out that it helps with this issue to use alpha=1 when setupPose!=0 but it also breaks a bunch of other things so I haven't yet found a good workaround.
Initially the first keyframe was the same between both animations but I tried changing it, which didn't help also.
Since it is quite difficult to find a workaround for this issue, I would suggest that this is a high-priority issue.

**Comment by snake5** [comment] 2017-05-11 10:30
Searched the forums, found this:
http://esotericsoftware.com/forum/Mix-creating-unexpected-behavior-in-new-version-7412?sid=cc7dad20b4bd159d49060d42c7dab26e&p=37952&hilit=mixing+bug#p37952
https://gist.githubusercontent.com/pharan/cffdc3b2aee9288c9ca8b4ab94ee97d2/raw/ec10be8fe92900d1dcb6bc22cad0a1e6fa21c803/AnimationState.cs

It appears to be different from spine-c and the differences suggest that the issue might be fixed there. I'll check later.

**Comment by snake5** [comment] 2017-05-11 17:55
Looks like this issue is fixed in 3.6 beta.

**Comment by snake5** [comment] 2017-05-11 18:22
Unfortunately I've found another bug of the same kind in latest 3.6-beta source.

When mixing overlaps (like when quickly switching the animation twice), there is still unwanted jittering.

https://drive.google.com/open?id=0Bz3gNbfHFo_lMU14V1FIWjY4ckU
Please download the video as the built-in player is showing a damaged copy instead of the 60fps original.

I'm using the same character files as above to reproduce the issue: [player_char.zip](https://github.com/EsotericSoftware/spine-runtimes/files/992262/player_char.zip)

**Comment by NathanSweet** [comment] 2017-05-11 19:26
The skeleton is not enough info to reproduce the problem. First ,can you reproduce the problem in [Skeleton Viewer](http://esotericsoftware.com/spine-skeleton-viewer#Download)? If so, please list the exact steps to do so.

Note if you are not using multiple mixing (the default) then you will see a jump if you interrupt a mix. If you enable multiple mixing, you won't see a jump when interrupting a mix, but you may see a dip toward the setup pose when switching animations.

**Comment by snake5** [comment] 2017-05-11 19:51
Yes, I can reproduce the problem in Skeleton Viewer. 
[This is the initial state](https://cloud.githubusercontent.com/assets/1819544/25968986/019c7180-369c-11e7-9bb0-5dff037e80da.png), then I quickly switch the animation to "ladder_jump" and back.

> Note if you are not using multiple mixing (the default) then you will see a jump if you interrupt a mix. If you enable multiple mixing, you won't see a jump when interrupting a mix, but you may see a dip toward the setup pose when switching animations.

It probably is the jump from interrupting the mix. Neither option works for me then. I need smooth transitions regardless of how or when the animation is started, without any deviations in motion. Saving the previously mixed pose would probably work for me.

**Comment by NathanSweet** [comment] 2017-05-11 20:04
If you are interrupting a mix then the expected behavior is as I described. Unfortunately there is no possibility to have both multiple mixing and to avoid dipping toward the setup pose. Maybe it would get you closer to the desired behavior if you turned multiple mixing on and off based on the state your character is in? Eg, while on the ladder turn multiple mixing on, otherwise set it to off.

**Comment by snake5** [comment] 2017-05-11 20:22
Either behavior looks weird in this particular transition, multiple mixing looks even worse. The gif above shows what happens with multiple mixing. It was created with a different version of the runtime but I just checked that it is in fact the same behavior as with multiple mixing in this one.

By the way, I don't need multiple mixing as in mixing more than two animations/poses, I just need all transitions to be smooth. :)

For now I could try to limit the frequency of switching in the most obvious cases but eventually I'd like to get rid of this limitation as it seems hard to manually fix this for every possible case that might appear.

**Comment by NathanSweet** [comment] 2017-05-11 21:07
I don't see any snapping with the repro steps you have given:
![](http://n4te.com/x/1897-jump.gif)
Please make it clear what the problem is.

If you are mixing A -> B and during the mix you set C (or A again, or any animation), then to avoid a jump you *do* need to mix more than 2 animations. You need to continue mixing A -> B and then mix the result with C.

Using a shorter mix time may help, since it is less likely to interrupt the mix. You probably don't need the 1 second you have set in Skeleton Viewer.

**Comment by snake5** [comment] 2017-05-12 05:27
![output](https://cloud.githubusercontent.com/assets/1819544/25982972/d126410e-36e9-11e7-9e4a-4c595eebcf78.gif)
Here it is.

There not only seems to be the regular snapping but the bones are moving outside of the expected path.

As for multiple mixing, there are two possible options:
1) implement it so that there is no dipping (first animation sets the value without blending and following animations blend on top of that)
2) it is possible to save the pose created in the previous mix, then interpolate between that and the new animation.

> Using a shorter mix time may help, since it is less likely to interrupt the mix.

My mix duration value is 0.1, it's just easier to reproduce by clicking around with 1.0. Oddly enough, the bug looks worse with smaller values.

**Comment by NathanSweet** [comment] 2017-05-12 07:32
You example GIF has multiple mixing disabled. There is no snapping with it enabled.

**Comment by snake5** [comment] 2017-05-12 07:55
I know, I can't use multiple mixing here, it looks weird.
![weird](https://cloud.githubusercontent.com/assets/1819544/25939045/25a77b36-363a-11e7-8a24-63383df1be0a.gif)
Hands are moving off the ladder, which is unacceptable, since both animations don't include this motion.

**Comment by NathanSweet** [comment] 2017-05-12 09:01
OK, I wanted to be sure. Unfortunately we haven't been able to come up with a solution for non-dipping, multiple mixing. You might try playing `ladder_prepjump` on track 0, then play `ladder_jump` on track 1. To cancel `ladder_jump`, call AnimationState [setEmptyAnimation](http://esotericsoftware.com/spine-api-reference#AnimationState-setEmptyAnimation) on track 1.

**Comment by snake5** [comment] 2017-05-12 18:15
OK, thanks, that worked. I hope I won't run out of tracks this way though. It's a decent backup solution to keep in mind.

Multiple mixing seems like an easy problem (at least it was for the few animation systems that I'd written before) so I'm looking into it anyway. Dipping is probably a result of trying to use some kind of weighted blending instead of chronologically ordered interpolation, which is the correct solution.

Current patch: [AnimationState.c.v1.patch.txt](https://github.com/EsotericSoftware/spine-runtimes/files/997524/AnimationState.c.v1.patch.txt)
I'm testing it with multiple mixing enabled.
It solves the particular issue that I had with ladder animations but it has also created three new issues that I'm looking into:
- bone states (at least rotation) from previous animations getting stuck if there are no matching timelines in the next animation
- first frame seems to be delayed or something, leading to desync in situations when character position change must be in sync with root bone position change, to avoid single frame character displacement
- arm track animations are sometimes not blending fully anymore

These issues may or may not be overlapping or the same, the cause for each is still unknown.

**Comment by NathanSweet** [comment] 2017-05-12 20:52
We would certainly welcome a proper fix for non-dipping, multiple mixing! AnimationState is a bit of a beast, as you've found. For easy testing, I suggest running Skeleton Viewer in spine-libgdx from source. You can use [this JSON](http://n4te.com/x/1203-mixing.json) in Skeleton Viewer. Some tests that commonly fail:
1) bone1 -> bone2, interrupt mix to bone3
2) bone1 -> bone2, interrupt mix back to bone1
3) bone1 -> bone1-dupe (is a copy of the same animation, tests for dipping)

Also, there is an AnimationStateTest class in spine-libgdx, but it mostly only tests AnimationState events.

I'll close this issue for now but we can continue discussion about AnimationState here if you like, or via the forum or email: contact@esotericsoftware.com

**Comment by snake5** [comment] 2017-05-13 06:38
I think I've managed to fix all of those issues at the same time (they seem to have been just one and the same issue).

The patch is still unfinished though. Scratch buffer should be dynamically allocated in animation state, all types of timelines should have an UID, and scratch buffer should be a bit vector to save memory.

[multiple_mixing.patch.txt](https://github.com/EsotericSoftware/spine-runtimes/files/998384/multiple_mixing.patch.txt)

I'll try to port it to spine-libgdx soon, to test with your JSON example.

**Comment by NathanSweet** [comment] 2017-05-13 09:12
Interesting, though doing it in spine-c makes it harder to evaluate. Ideally changes are done to the reference implementation, which is spine-libgdx, then we port from there to the other runtimes.

Note that timelines already have an ID (`getPropertyId`). It's used to calculate timelinesFirst and timelinesLast, which appear to do something similar to what your channelStates does.

**Comment by snake5** [comment] 2017-05-13 11:42
I have ported the unfinished fix to the libgdx runtime.
Thanks to your test case, I found and fixed another bug or two.

[multiple-mixing-libgdx.patch.txt](https://github.com/EsotericSoftware/spine-runtimes/files/998575/multiple-mixing-libgdx.patch.txt)

I have tried all of the tests you suggested and they look good to me. Can you confirm that the patch works for you as well?

**Comment by NathanSweet** [comment] 2017-05-13 12:51
Again, I think `timelinesFirst` and `timelinesLast` replace your `channelStates` -- they store if a timeline is the first or last one to be applied to a property. They are calculated only when the animations change, which is infrequent enough that their computation cost can be ignored. You shouldn't need a whole separate system to calculate property IDs, nor another array to store them per timeline.

The provided patch is not easily applied. Can you please create a patch in the root of the spine-rutimes repo folder that can be applied with `git apply patch.diff`?

**Comment by snake5** [comment] 2017-05-13 13:38
I don't need to know whether a timeline is first or last to be applied, but whether the next animation will apply the same timeline. I did not find such data there.

There is a difference in the [animation1] -> [empty] -> [animation2] case. The animation [empty] following [animation1] does not contain the same timelines, but it is not last according to the data available.

Also, I'm not storing property IDs anywhere, they are indices for a boolean array.

That said, I'm sure the system can be refactored to produce the data I need, I just didn't want to bother for a prototype, caching systems are inherently more unreliable than those that don't do any caching, and I don't like the possibility of having to debug multiple systems at once.

As for the patch, I did create it from the root, it's just Git being annoying again. Changing the file's line endings to Unix-style should make it work. Alternatively, you can try this one:
[multiple-mixing-libgdx.patch.txt](https://github.com/EsotericSoftware/spine-runtimes/files/998645/multiple-mixing-libgdx.patch.txt)
I have checked that it can be applied.

**Comment by NathanSweet** [comment] 2017-05-13 16:25
Re timelinesFirst/Last vs channelStates, gotcha. Thanks, the patch worked. It seems to work well in Skeleton Viewer for most cases, which is great, kudos! I did find one failure:
`bone1` -> `bone1-dupe`, then interrupt with `bone2`: bone1 rotation snaps when the `bone1` -> `bone1-dupe` mix completes.

**Comment by snake5** [comment] 2017-05-13 17:11
Hmm, indeed, I can reproduce that issue. I'll look into it soon.

**Comment by snake5** [comment] 2017-05-13 19:09
Trying a slightly different approach.
[multiple-mixing-libgdx-v2.patch.txt](https://github.com/EsotericSoftware/spine-runtimes/files/998871/multiple-mixing-libgdx-v2.patch.txt)

It should work with all of the test cases mentioned so far.

Only rotation timelines are supported by this patch. If the approach works acceptably, it should be easy to add support for others as well.

I found some issues when blending between 180 degree differences but some of them were also present in the original Skeleton Viewer so I'm guessing that it's not particularly important to support such edge cases and some might be triggered by pre-existing bugs.

**Comment by snake5** [comment] 2017-05-14 06:37
I've implemented the fix for all timelines.
[multiple-mixing-libgdx-v3.patch.txt](https://github.com/EsotericSoftware/spine-runtimes/files/999144/multiple-mixing-libgdx-v3.patch.txt)
There are some parts that I'm doubtful about (like scale timeline sign logic and the handling of event/draw order/attachment timelines) but it's difficult to say if everything's OK without thorough testing.

Here's a translation timeline test (created from rotation timeline test):
[1203-mixing-tr.json.txt](https://github.com/EsotericSoftware/spine-runtimes/files/999145/1203-mixing-tr.json.txt)
I've tried all mentioned test cases, everything looks good here as well.

As opposed to my previous attempt that triggered the "`bone1`->`bone1-dupe` -> `bone2`" bug, this should be a complete and mathematically accurate fix. I was initially trying to avoid it as it would result in a lot more changes. But I now see that there was no way to do things correctly with the existing timeline code.

The problem was in that I needed to blend [unknown state] -> [animation] -> [empty (setup pose)] from the context of [animation], and a single interpolation wasn't going to do both mixes.
The [empty] --(1)-> [animation] --(2)-> [empty] case worked because it can be done with a single interpolation, with factor mix1*(1-mix2).

**Comment by NathanSweet** [comment] 2017-05-16 03:22
Thanks for digging into this, I know it's quite a painful thing to think through all the cases without losing sanity. Your solution using the `mixOut` parameter is very interesting. I'm really impressed you found something that works in nearly all cases!

There does seem to be some issues with multiple tracks. I've updated the [test JSON](http://n4te.com/x/1948-6b1G.txt) (similar to how you did). Try: track 0 `m1`, track 1 `m1->empty`. Expected: m1 keeps being fully applied (bones don't move). Actual: m1 mixes to the setup pose, then snaps back after the mix. I'm not sure what the fix would be, I guess avoiding `mixOut` if the scenario can be detected.

Internally we've also been looking at ways to solve the problem. We came up with a pretty close solution, check it out in b882fb8c51787eee27f88433252a6de16b77b134. Part of the idea is to simplify the problem by not applying the dip fix for non-adjacent track entries. Ie, `a -> b, c` where a and c key `x`, since a and c aren't adjacent, don't apply the dip fix for `x`. This simplifies many cases and in practice it doesn't appear to be important that `x` dips, since the `a -> b` transition was already changing `x`. There is one case that fails, which is `a -> b, a` where both key `x`: the dip fix is applied to `a -> b` but it is mixed out, causing a dip. There's probably a way to detect that, but my brain is mush at the moment. The dip fix is mixed out to solve `a -> b, c` where a and b key `x`.

**Comment by snake5** [comment] 2017-05-16 07:17
Hmm, I forgot about multiple tracks. I can reproduce your issue. At the moment, I can only think of a sub-optimal solution (storing the initial state for all bones, slots etc. before applying each track) but I'll keep working on it.

I also considered applying the mix-out value to all preceding timelines until it's missing from a track entry but the math doesn't quite make sense to me yet. The result would probably be smooth but inaccurate and require an array of these values for each channel/property ID. I'll try to play around with the equations, maybe I can get something more accurate out of them.

About b882fb8 - one of the things I noticed is that in the original test case (1203-mixing.json) as well as 1203-mixing-tr.json, [bone1] -> [bone1-dupe] -> [bone1] is still dipping. It's probably the `a -> b, a` case that you mentioned.

**Comment by NathanSweet** [comment] 2017-05-16 23:26
BTW, in 02660ddd0afc29fe85076a424c91ab3dff2cdb6d we managed to solve the `a -> b, a` case by finding the first animation that will be applied that *doesn't* key the property and using that animation's mix to mix out the dip fix (see `timelineDipMix`). I feel pretty OK but AnimationState now (as much as that is possible, given the monster that it is).

**Comment by snake5** [comment] 2017-05-17 06:38
That's great news. I've checked all test cases known so far and they all look good, well done. Can't wait to get a C runtime port in my game. :)

**Comment by badlogic** [comment] 2017-05-19 09:07
@snake5 I've ported the latest fixes to spine-c on the 3.6-beta branch. Let us know if you give it a whirl and find any problems!

**Comment by snake5** [comment] 2017-05-19 19:15
Thanks! I have tried it now and it mostly works well for me.

There is a way to trigger the dipping problem but it requires very rapid animation switching. It's not nearly as simple as it used to be.

It can be seen here:
![s2bug](https://cloud.githubusercontent.com/assets/1819544/26263131/0f529418-3ce0-11e7-9f95-66eb9c1d11a9.gif)

I'm holding D and tapping W very quickly. Every press changes the animation and every release changes it back.

Due to the speed requirement, it's probably unlikely to be reproducible in Skeleton Viewer and would need some kind of automation instead.

**Comment by NathanSweet** [comment] 2017-05-19 20:22
Hmm. It can be seen in SV by setting the speed to ~0.12 and the mix to 1, then change from `m1` to `m1-dup` repeatedly. You can see at the bottom that many "mixing from" track entries are being kept:
![](http://n4te.com/x/1992-0o0J.png)
Once you get more than 5, AnimationState#updateMixingFrom starts removing the oldest entries. The limit is to prevent a very long mixing from linked list. If you remove the limit of 5 (or eg set it to 5000) then you won't see the problem anymore. This isn't a real fix though, since with long mix durations the linked list could continue to grow until OOM. Plus, do you really want to be applying dozens of animations to pose a single skeleton?

We keep mixing from entries until all are finished because they are needed to prevent snapping when the dip fix is used. If it weren't for the dip fix, we could remove the last (`from.mixingFrom == null`) finished entry immediately. To see the problem, try changing the AnimationState#updateMixingFrom code to this:
```
if (entry.mixTime > 0 && (entry.mixTime >= entry.mixDuration || entry.timeScale == 0)) {
	if (from.mixingFrom == null) {
		entry.mixingFrom = null;
		queue.end(from);
	}
	return finished;
}
```
Then try `m1->m1-dup,m2` or `m1->m1-dup,m1` and you'll see snapping.

AnimationState#setTimelineData could set a TrackEntry#dipFix boolean to true if *any* of its timelines use the dip fix. If false, updateMixingFrom() can dispose the entry immediately when last and finished. However, most entries probably use the dip fix, so this doesn't help anything in that common case.

When an entry that uses the dip fix is finished, there may be some state we can store so we don't have to keep applying it. The dip fix is at the timeline level, so updateMixingFrom() would have to find each timeline that uses the dip fix, then find the timeline in the next entry and set some state there to fix the snapping. Maybe you'd like to give that a try?

**Comment by snake5** [comment] 2017-05-20 08:41
Sure, I can look into it.

**Comment by snake5** [comment] 2017-05-23 06:48
This patch works for me in my game (should be small enough for retyping in Java, I didn't test it there yet):
[clean_fix_v2.patch.txt](https://github.com/EsotericSoftware/spine-runtimes/files/1021122/clean_fix_v2.patch.txt)

I am not sure why there needs to be one more supposedly unused track entry behind the one removed but that's what seems to be working for me right now. Also, the timelines for both animations may be the same so there could be more to it. I'll look into it later.

Either way, after thinking about it for a while, I would suggest to abandon hacks and instead rewrite the entire thing using intermediate track mixing with alpha value for each timeline channel. It may cost a bit more but the code and logic should be a lot more easy to understand.

**Comment by NathanSweet** [comment] 2017-05-23 11:12
Sorry, I didn't get notifications see about your edits 3 days ago, only when you posted a new message.

The patch looks interesting, I'll check it out today, thanks!

It's too large of a change to consider additive intra-track mixing for 3.6. It wouldn't really simplify AnimationState though, since we'd still need what we currently have for mixing tracks. Also, it seems we would need to calculate the poses of 2 tracks using additive, then combine them using layered (the current mixing). Needing to store the entire skeleton pose twice is unfortunate.

**Comment by snake5** [comment] 2017-05-23 20:41
No worries, that was the idea. I didn't want to disturb anyone before I had anything concrete.

As for mixing - yeah, any major changes are too big for now. Come to think of it, the alpha value idea probably won't work here as cleanly as I expect and I should instead probably finish that patch I worked on a week ago.

**Comment by NathanSweet** [comment] 2017-05-24 01:41
I played with using `totalAlpha` a bit. It needs to happen in update, since apply should not have side effects (AnimationState may be applied to multiple skeletons between updates). Also setting `interruptAlpha` appears to be needed. I committed it in a69f9d579f33134659ecd8b7f36a443f6648fb08. It works in most scenarios, but there is still one that snaps: `m1 -> m1-dup, m2, m1-dup, m1`. The snap is larger if you pause before adding the last animation. This case is using the dip fix, then an animation that doesn't key the dip fix property, then using the dip fix again. It can be seen with spineboy: `idle, jump, test, jump, idle` (the test animation doesn't key most of the bones). In practice this snap may not be encountered very often, though it would still be nice to fix it.

**Comment by snake5** [comment] 2017-05-24 20:34
Looks interesting. I can only really check the changes from C++ though. As for the snapping scenario, I'm not sure how much can be done without heavily increasing track entry count. The necessary animation count to trigger it is 5 already, which was the limit previously.

**Comment by badlogic** [comment] 2017-05-24 20:38
The changes are already in spine-c!

**Comment by snake5** [comment] 2017-05-24 21:13
Huh, looks like I missed it, sorry. Anyway, I tested it now and all the bugs that I could reproduce seem to be gone now. Good job!

So as far as I'm concerned, the issue can be closed now. If you want, I can still finish that more than a week old patch though.

**Comment by badlogic** [comment] 2017-05-25 06:26
Not sure it's worth it at this point for you to finish the patch. We'll tackle intra-track mixing in a separate issue for 3.7.

Really appreciate all your help with this!

**Closed by badlogic** 2017-05-25 06:26 UTC
Labels: runtimes
