### ISSUE TITLE
[godot] Can't compile Godot 3.4 source with Spine 4.2 beta runtimes

### ISSUE THREAD

**Issue by tarragonfly** [EsotericSoftware/spine-runtimes#2079] opened 2022-05-08 23:17 UTC
<details>
  <summary>cmd log</summary>
```
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\Animation.cpp
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\AnimationState.cpp
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\AnimationStateData.cpp
Animation.cpp
modules\spine_godot\spine-cpp\src\spine\Animation.cpp(30): fatal error C1083: Cannot open include file: 'spine/Animation.h': No such file or directory
AnimationState.cpp
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\Atlas.cpp
modules\spine_godot\spine-cpp\src\spine\AnimationState.cpp(30): fatal error C1083: Cannot open include file: 'spine/AnimationState.h': No such file or directory
[Initial build] AnimationStateData.cpp
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\AtlasAttachmentLoader.cpp
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\Attachment.cpp
modules\spine_godot\spine-cpp\src\spine\AnimationStateData.cpp(30): fatal error C1083: Cannot open include file: 'spine/AnimationStateData.h': No such file or directory
Atlas.cpp
[Initial build] AtlasAttachmentLoader.cpp
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\AttachmentLoader.cpp
modules\spine_godot\spine-cpp\src\spine\Atlas.cpp(30): fatal error C1083: Cannot open include file: 'spine/Atlas.h': No such file or directory
Attachment.cpp
modules\spine_godot\spine-cpp\src\spine\AtlasAttachmentLoader.cpp(30): fatal error C1083: Cannot open include file: 'spine/AtlasAttachmentLoader.h': No such file or directory
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\AttachmentTimeline.cpp
modules\spine_godot\spine-cpp\src\spine\Attachment.cpp(30): fatal error C1083: Cannot open include file: 'spine/Attachment.h': No such file or directory
AttachmentLoader.cpp
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\Bone.cpp
[Initial build] AttachmentTimeline.cpp
Compiling ==> modules\spine_godot\spine-cpp\src\spine\BoneData.cpp
modules\spine_godot\spine-cpp\src\spine\AttachmentLoader.cpp(30): fatal error C1083: Cannot open include file: 'spine/AttachmentLoader.h': No such file or directory
modules\spine_godot\spine-cpp\src\spine\AttachmentTimeline.cpp(30): fatal error C1083: Cannot open include file: 'spine/AttachmentTimeline.h': No such file or directory
[Initial build] Bone.cpp
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\BoundingBoxAttachment.cpp
[Initial build] modules\spine_godot\spine-cpp\src\spine\Bone.cpp(30): fatal error C1083: Cannot open include file: 'spine/Bone.h': No such file or directoryBoneData.cpp

[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\ClippingAttachment.cpp
BoundingBoxAttachment.cpp
modules\spine_godot\spine-cpp\src\spine\BoneData.cpp(30): fatal error C1083: Cannot open include file: 'spine/BoneData.h': No such file or directory
[Initial build] Compiling ==> modules\spine_godot\spine-cpp\src\spine\ColorTimeline.cpp
ClippingAttachment.cpp
modules\spine_godot\spine-cpp\src\spine\BoundingBoxAttachment.cpp(30): fatal error C1083: Cannot open include file: 'spine/BoundingBoxAttachment.h': No such file or directory
ColorTimeline.cpp
modules\spine_godot\spine-cpp\src\spine\ClippingAttachment.cpp(30): fatal error C1083: Cannot open include file: 'spine/ClippingAttachment.h': No such file or directory
modules\spine_godot\spine-cpp\src\spine\ColorTimeline.cpp(30): fatal error C1083: Cannot open include file: 'spine/ColorTimeline.h': No such file or directory
scons: *** [modules\spine_godot\spine-cpp\src\spine\Animation.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AnimationState.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AnimationStateData.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\Atlas.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AtlasAttachmentLoader.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\Attachment.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AttachmentLoader.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\AttachmentTimeline.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\Bone.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\BoneData.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\BoundingBoxAttachment.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\ClippingAttachment.windows.tools.64.obj] Error 2
scons: *** [modules\spine_godot\spine-cpp\src\spine\ColorTimeline.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
[Time elapsed: 00:00:33.050]
```
</details>

**Comment by badlogic** [comment] 2022-05-27 09:19
Did you run `setup.bat/.sh` in the `spine-godot` directory? That's required for spine-cpp to be copied over to the module. What version of Scons are you running?

**Comment by josiahdowdy** [comment] 2022-05-28 21:27
@tarragonfly when I don't use the setup.sh I get the same errors, but it works when using setup.sh on 3.4.4-stable. 
On mac, in your terminal, cd into the folder godot-spine.
Then drag the 'setup.sh' file into your terminal and type either '3.4.4-stable' or 'master' (note: master hits a bug for me, something about VMap). Press enter.
It will install godot with the godot_spine module.

Then, in order to make a clickable app to launch, run:
cp -r misc/dist/osx_tools.app ./Godot.app   (from root godot)
mkdir -p Godot.app/Contents/MacOS
cp bin/godot.osx.tools.64 Godot.app/Contents/MacOS/Godot
chmod +x Godot.app/Contents/MacOS/Godot

(note: in line 3, the name of your godot might be different)

Let me know if you're still having issues. You might need to update Scons.

**Comment by badlogic** [comment] 2022-05-30 11:17
I've tried to repro this using `setup.sh` on both macOS and Windows. All of these compile and work as intended:

```
./setup.sh 3.4.4
./setup.sh 3.4
```

We currently do not compile against master (4.0) without errors, as that branch keeps breaking things all the time and we'll wait until things have settled.

If you can provide me exact steps on how to reproduce your compilation errors, please post them here. In the meantime, I'm closing this issue out.

**Closed as completed by badlogic** 2022-05-30 11:17 UTC
Labels: bug
