### ISSUE TITLE
[runtimes] MixBlend.Add behavior: addAnimation() and base-layer mix snapping

### ISSUE THREAD

**Issue by Jamez0r** [EsotericSoftware/spine-runtimes#1746] opened 2020-08-23 20:37 UTC
Repro Unity Project: https://drive.google.com/file/d/1Q7REgQ7i85eQQD_VcTnX3zZahPz1vow9/view?usp=sharing
Spine Project used in Repro: https://drive.google.com/file/d/13d3P5_ksWR8cFxgHVgxXLyDGjMZCI7J3/view?usp=sharing
Base-layer track animations ("Iddle" and "Attack") both have Transform keys for all bones used in the additive-layer animation ("HitStop_L").
Using latest version of Spine-Unity runtime.

Comments are in the code for the script that is on the Spine GameObject, explaining things in better detail.

Issue # 1: Calling AddAnimation() on a MixBlend.Add track multiple times will only play the animation once.
Issue # 2: The configuration of using an EmptyAnimation to 'clear' a MixBlend.Add track when it finishes causes snapping issues on the lower-level tracks.

My goal is to be able to play an "impact" animation (with additive mixblend) when you hit an enemy. The only configuration I could get that doesn't cause the mix-snapping issue on the base-layer tracks is to completely clear the track each time before playing the MixBlend.Add animation.

**Comment by NathanSweet** [comment] 2020-08-24 02:48
I haven't looked at the Unity repro project, but some comments:

### Issue 1
Is the track empty when you call `addAnimation` multiple times, and do you call it multiple times without applying the AnimationState? Note docs for [addAnimation](http://esotericsoftware.com/spine-api-reference#AnimationState-addAnimation2):

> If the track is empty, it is equivalent to calling setAnimation.

And [setAnimation](http://esotericsoftware.com/spine-api-reference#AnimationState-setAnimation2):

> If the formerly current track entry was never applied to a skeleton, it is replaced (not mixed from).

This behavior is because there is little use mixing from an animation that never really began.

### Issue 2
Both Preview and Skeleton Viewer use `setEmptyAnimation` when you deselect an animation for a track. I don't see this behavior in the Preview view. Could be a spine-csharp bug or the repro is somehow different.

**Comment by Jamez0r** [comment] 2020-08-24 03:09
> Is the track empty when you call `addAnimation` multiple times, and do you call it multiple times without applying the AnimationState?

I set a button ("p") to call addAnimation (for the MixBlend.Add track). Pressing "p" the first time will play the animation, but pressing it again at any time after that does nothing.

Sorry, I had better notes in the comments of the script in the Unity Project, maybe I should have copy/pasted them here

**Comment by NathanSweet** [comment] 2020-08-24 03:11
OK, no worries. We'll see what Harri comes up with when he has time to check out the project.

**Comment by Jamez0r** [comment] 2020-08-24 03:14
Made a quick pastebin for the code: https://pastebin.com/8wM6gMtv

**Comment by HaraldCsaszar** [comment] 2020-08-24 19:01
Thanks for opening the detailled issue with the reproduction package attached.

Regarding your issues:

### Issue 1
The animation is played back properly, it's just your `MixDuration` of `1.0` second which mixes it in for such a long time that the impact is added with e.g. factor `0.1` at the start and when it reaches `1.0` there is no impact left to overlay from the `HitStop_L` animation.

### Issue 2
Unfortunately I could also not reproduce this issue in Unity. On the other hand it could be that we just did not notice it, since the `SetupPose` is quite similar to the played animations. Could you perhaps create an animation that shows the difference in a better way?

**Comment by Jamez0r** [comment] 2020-08-24 19:13
Hey Harald, thanks for taking a look!

Issue 1: Whoops, thats embarassing. Total oversight on my part, sorry!

Issue 2: Sure, its a bit weird with what you have to do to get the issue to happen. I'll exaggerate the animations so its easier to see and reupload the project, and I can also take a quick video of it and say what buttons I'm pressing.

**Comment by Jamez0r** [comment] 2020-08-24 20:34
Video: https://www.youtube.com/watch?v=t1_ZLRhGEAc&feature=youtu.be

Updated Repro Project (with simplified/exaggerated animations)
Unity Project: https://drive.google.com/file/d/1-7FfRjzoWuvFbSPCRKRSBL8FSk_IyvPa/view?usp=sharing
Spine Project: https://drive.google.com/file/d/1jqCe67gxwDN3_DvJ8sM4y5Da_px2Pw6n/view?usp=sharing

Note: The "arms_outward_loop" and "arms_together_loop" both have all transforms keyed for all bones on the first frame.
Note 2: This snapping behavior is happening on all 3 of my characters that use additive blending.

Thank you guys for the help!

**Comment by Jamez0r** [comment] 2020-08-24 20:42
Looking at the video, and it seems like the "snapping" might be a mix going from the Setup Pose into the "arms" animations. I should have placed the arms in the Setup Pose at an even more obvious position.

**Comment by Jamez0r** [comment] 2020-08-24 20:51
Ok here we go - I changed the Setup Pose to have the characters arms sticking straight upward. Everything else is the same. Much more clear to see whats happening - it does appear that when the "snapping" is happening, that it is mixing from Setup Pose into the animation

Updated Projects with Arms Pointing Up in Setup Pose:
Unity Project: https://drive.google.com/file/d/1sY3BTKGWr5kW0FFMkZehRo6ky8trNQsu/view?usp=sharing
Spine Project: https://drive.google.com/file/d/1UnidbJlY8C3Xatb4rmIWKrWzbsCAKFyu/view?usp=sharing

**Comment by HaraldCsaszar** [comment] 2020-08-25 15:54
Thanks for uploading the new files. Unfortunately the policy on the folder in google drive seems to be too restrictive, access is not granted out of the box. Please provide us with the required access rights.

**Comment by Jamez0r** [comment] 2020-08-25 16:13
Sorry about that, really strange that it wasn't shared correctly. I gave access from the email requests and updated the settings on the links.

**Comment by HaraldCsaszar** [comment] 2020-08-25 16:42
Thanks for the update, we can now reproduce the issue.

**Comment by HaraldCsaszar** [comment] 2020-09-03 11:33
Issue also occurs on libgdx reference implementation. A reduced test asset and automated example code have been created, see description below.

Problem description (note: code below may be easier to read than prose text here):
A combination of `setAnimation()` and `addEmptyAnimation()` calls was found that unexpectedly mixes SetupPose (shows dipping) in a transition.
When directly calling `setAnimation()` for an additive animation on layer 1 twice, each time followed by `addEmptyAnimation()`, and then calling `setAnimation()` to start a normal base animation on layer 0, waiting some frames and again starting the same base animation, SetupPose is mixed in the transition.

Reproduction steps in SkeletonViewer (reproduces every time):

1) Unpack the zip package `files/issues/1746_MixBlendAddSnapping.zip` and load the `arboreal_terror.json` file in SkeletonViewer. This file has the arm of the character pointing upward in setup pose, other animations point it sideways or downward.

2) Add the following code to the `SkeletonViewer` class:

```
	// add attribute to SkeletonViewer class
	int frameCounter = 0;
```

```
	// render() {
		// at the top of SkeletonViewer.render(), e.g. after Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT)
		// these frame values might need to be changed if the problem does not reproduce out of the box
		if (frameCounter++ == 0)
			baseAnim(state);
		if (frameCounter == 30)
			prepareProblem();
		if (frameCounter == 60)
			triggerProblem();
```

```
	// add methods that reproduce the problem.
	void prepareProblem() {
		additiveAnim(state);
		additiveAnim(state); // without this second animation call the problem does not occur
		baseAnim(state); // Note: problem does not occur when this line is moved to the top of this method before additiveAnim()!
		state.update(1.0f);
	}
	
	void triggerProblem () {
		// starting animation which is now mixed from SetupPose
		baseAnim(state);
	}
	
	void baseAnim(AnimationState state) {
		state.setAnimation(0, "Arms_Together_Loop", true);
	}
	
	void additiveAnim(AnimationState state) {
		TrackEntry impactTrack = state.setAnimation(1, "Impact_Animation", false);
		impactTrack.mixBlend = MixBlend.add;
		state.addEmptyAnimation(1, 0.2f, 0);
	}
```

3) Start SkeletonViewer. After 60 frames the transition to the base animation is started, but mixing from SetupPose with the arm transitioning from upward (setup pose) to downward pose. Any upward facing arm position (from setup pose) is not expected to be showing here.

**Comment by HaraldCsaszar** [comment] 2020-09-03 11:35
Removed `in progress` label since this problem is no longer limited to spine-unity only but instead shall be addressed in the reference implementation as well.

**Comment by NathanSweet** [comment] 2021-06-15 02:20
Sorry for the long delay. Quite a complex reproduction was needed for such a simple fix!

**Closed as completed by NathanSweet** 2021-06-15 02:20 UTC
Labels: bug
