### ISSUE TITLE
[ue4] SpineWidget not displaying correctly on OpenGLES 2.0 & 3.1 

### ISSUE THREAD

**Issue by GloryOfNight** [EsotericSoftware/spine-runtimes#1424] opened 2019-07-30 12:55 UTC
Latest spine-runtimes 3.8-beta. 

Expected:
![unknown](https://user-images.githubusercontent.com/23162722/62129897-7d881700-b2e0-11e9-8e3a-cd128c2bc260.png)
Result:
![Screenshot_20190730-152714](https://user-images.githubusercontent.com/23162722/62129925-8bd63300-b2e0-11e9-841c-0e0a5ed09ea0.png)
Also video link:
[link](https://drive.google.com/file/u/1/d/1aIGameJcilr37QQfB7mCcxft4HPLX-U8/view?usp=drive_open)

Tested on mobile with opengles 2.0 & es3.1 support. Issue the same on both. 
Mobile HDR off.

**Comment by badlogic** [comment] 2019-07-30 12:56
Duplicate of https://github.com/EsotericSoftware/spine-runtimes/issues/1421

**Closed as completed by badlogic** 2019-07-30 12:56 UTC

**Comment by badlogic** [comment] 2019-07-30 13:34
Thank you for reporting. This is fixed in the 3.8-beta branch.
