### ISSUE TITLE
[spine-c] memory leaking

### ISSUE THREAD

**Issue by mrpuzzler** [EsotericSoftware/spine-runtimes#776] opened 2016-11-25 10:48 UTC
still leaking at spAnimationState_apply

**Comment by mrpuzzler** [comment] 2016-11-25 10:49
Also getting leaks on _spAnimationState_resizeTimelinesFirst for int* newTimelinesFirst = CALLOC(int, newSize);

and _spAnimationState_resizeTimelinesRotation - also leaking ...

Probably happens while changing state

**Comment by badlogic** [comment] 2016-11-25 11:06
What leak detector are you using? Need to repro your baseline.

**Comment by jpoag** [comment] 2016-11-25 14:09
Ok, I can reproduce and I think I've figured out what's happening.

Here's a LOG of the Events generated, please forgive me there are 3 separate animations, one with a long queue of animations that gets set twice... sorry... will highlight the offending memory

> 08:43:26: [SP_ANIMATION_START: 09AAC488]
> 08:43:26: [SP_ANIMATION_START: 08176BC0]
> 08:43:27: [SP_ANIMATION_INTERRUPT: 09DF1990]
> 08:43:27: [SP_ANIMATION_END: 09DF1990]
> 08:43:27: [SP_ANIMATION_DISPOSE: 09DF1990]
> 08:43:27: [SP_ANIMATION_DISPOSE: 09DF1B28]
> 08:43:27: [SP_ANIMATION_DISPOSE: 080F63E8]
> 08:43:27: [SP_ANIMATION_DISPOSE: 080F65C8]
> 08:43:27: [SP_ANIMATION_DISPOSE: 07FCFEA8]
> 08:43:27: [SP_ANIMATION_DISPOSE: 07FD0040]
> 08:43:27: [SP_ANIMATION_START: **09AF9EF8**]
> 08:43:27: [SP_ANIMATION_INTERRUPT: 09AAC488]
> 08:43:27: [SP_ANIMATION_END: 09AAC488]
> 08:43:27: [SP_ANIMATION_DISPOSE: 09AAC488]
> 08:43:27: [SP_ANIMATION_START: 080F65C8]
> 08:43:27: [SP_ANIMATION_INTERRUPT: 08176BC0]
> 08:43:27: [SP_ANIMATION_END: 08176BC0]
> 08:43:27: [SP_ANIMATION_DISPOSE: 08176BC0]
> 08:43:27: [SP_ANIMATION_START: 09AAC488]
> 08:43:28: [SP_ANIMATION_INTERRUPT: **09AF9EF8**]
> 08:43:28: [SP_ANIMATION_START: 09DF1990]
> 
> System Shutdown...
> 
> Memory Leak Report for Fri Nov 25 08:43:28 2016
> 
> ..\..\ThirdParty\spine\AnimationState.c(755) : Leak 400 bytes @0x02F16688
> ..\..\ThirdParty\spine\AnimationState.c(765) : Leak 200 bytes @0x08176BC0
> ..\..\ThirdParty\spine\AnimationState.c(693) : Leak 112 bytes @0x **09AF9EF8**

Lines 755 and 765 are leaks on the spTrackEntry allocated on line 693.

In `_spAnimationState_setCurrent` our leaked object is interrupted and set as the `mixingFrom` object on the current entry.  At this point, mixingFrom is a floating pointer. That is, if mixingFrom is a weak reference, then there are only weakReferences to the pointer.  If mixingFrom is a strong reference, then it needs to be disposed of properly in

```
void _spAnimationState_disposeTrackEntry (spTrackEntry* entry) {
	FREE(entry->timelinesFirst);
	FREE(entry->timelinesRotation);
	if(entry->mixingFrom) _spAnimationState_disposeTrackEntry(entry->mixingFrom); // strong reference
	FREE(entry);
}
```


Because the system is shutdown before allowing the mixing to play out, the spTrackEntry is leaked.

**Comment by badlogic** [comment] 2016-11-25 15:08
Furthermore, the strong reference is broken in _spAnimationState_updateMixingFrom, which allows us to dispose of `entry->mixingFrom` in `_spAnimationState_disposeTrackEntry` irrespective of whether the track was interrupted and sends dispose event for the mixingFrom to the queue, or whether the entire animation state is disposed. I've added this fix via the latest commit. 

@mrpuzzler I'm still trying to figure out how  spAnimationState_apply and _spAnimationState_resizeTimelinesFirst/_spAnimationState_resizeTimelinesRotation are leaking.

**Comment by badlogic** [comment] 2016-11-25 15:09
See https://github.com/EsotericSoftware/spine-runtimes/commit/900001098b6917f10cac2ce7161c0bce90faf75b for the mixingFrom leak fix.

**Comment by jpoag** [comment] 2016-11-25 16:02
Confirmed, looks fixed on my end.  I'm stopping manually at where the leak was happening and then shutting down.  Event order looks the same where it was happening and still no leaks.

I'm not seeing spAnimationState_apply() leak, but I think that _spAnimationState_resizeTimelinesFirst/_spAnimationState_resizeTimelinesRotation leaks are result of a leaking spTrackEntry, right?  Are they used anywhere else?

**Comment by badlogic** [comment] 2016-11-25 16:35
I've reproduced leaking of timelinesFirst/timelinesRotation without the mixingFrom leak fix, but can't reproduce it with the mixingFrom leak fix. Based on the code involved in the allocation/deallocation of that memory, I can't see any other way for that memory to leak other than if a track entry isn't properly disposed.

Can you please apply the mixingFrom leak and see if you still get the timlinesFirst/timelinesRotation leak in your code base?

@mrpuzzler could you please also specify what is leaking in your code base in spAnimationState_apply? I can't detect any leakage via Instruments.

**Comment by mrpuzzler** [comment] 2016-11-25 17:05
Confirmed, can't reproduce it on my side too.

**Comment by badlogic** [comment] 2016-11-25 22:25
Awesome! Closing this out then. Thanks for your help folks, greatly appreciated!

**Closed by badlogic** 2016-11-25 22:25 UTC
Labels: bug, runtimes

**Comment by jpoag** [comment] 2016-11-25 22:32
No problem. The offer to write a unit test to automatically check this
still stands. Would make me a day or two.

Cheers.

On Nov 25, 2016 5:25 PM, "Mario Zechner" <notifications@github.com> wrote:

Awesome! Closing this out then. Thanks for your help folks, greatly
appreciated!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/EsotericSoftware/spine-runtimes/issues/776#issuecomment-263028400>,
or mute the thread

**Comment by badlogic** [comment] 2016-11-25 23:15
Happy with whatever you can throw at me!

**Comment by jpoag** [comment] 2016-11-27 22:30
Ok, I have an example test framework up and running:

https://dl.dropboxusercontent.com/u/37936036/spine-c-unit-tests.zip

This project is a 'set and forget' style project to run on a Continuous Integration server.  Mainly for leak detection and regression testing.  However, in reproducing the #776 bug, I created a InteruptMonitor class capable of reproducing these 'edge' cases.

I setup the CMakeLists to operate as a subfolder of the main trunk.  README.md contains more information.

**Comment by jpoag** [comment] 2016-11-27 22:31
[spine-c-unit-tests.zip](https://github.com/EsotericSoftware/spine-runtimes/files/615104/spine-c-unit-tests.zip)
In case problems with Dropbox.

**Comment by badlogic** [comment] 2016-11-28 10:53
Great! I'll try to integrate that in with CI sometime this week. Thanks for all your efforts, really appreciated!

**Comment by badlogic** [comment] 2016-11-28 14:44
@jpoag could we get a CLA from you so we can put the test suite into this repo? Just fill this out and send us a photo of the signed CLA to contact@esotericsoftware.com.

**Comment by jpoag** [comment] 2016-11-28 14:47
I forwarded the one I sent 2 years ago.

**Comment by badlogic** [comment] 2016-11-28 14:49
:D sorry and a huge thanks again!
