### ISSUE TITLE
[ue] Importing skeleton does not seem to work on 5.3.0

### ISSUE THREAD

**Issue by zydeas** [EsotericSoftware/spine-runtimes#2368] opened 2023-09-15 23:45 UTC
After creating a blank C++ project using Unreal 5.3.0 and getting the Spine plugin installed, I tried importing one of the sample skeletons into the project by importing the .json file specifically. Unfortunately, this does not seem to work, as only the texture appears in the content browser, inside a Textures folder. No other asset appears.

There was also an issue in SpineAtlasImportFactory.cs, where the file AssetRegistryModule.h was failing to include, breaking the build. I had to change that line to `#include "Runtime/AssetRegistry/Public/AssetRegistry/AssetRegistryModule.h"` to point to the actual file. Then the plugin built correctly. Other than that, I made no modifications to the source code.

(I am using the most current release downloaded from the releases tab)

**Comment by tiger404** [comment] 2023-09-16 19:57
Also did the same and got the same result. Please fix this as soon as possible.

**Comment by casper7609** [comment] 2023-09-21 07:14
Would this issue be solved soon? Having the same and if it takes some time, I will downgrade ue to 5.2 to work

**Comment by BjornGameDev** [comment] 2023-09-21 12:57
+1

**Comment by badlogic** [comment] 2023-09-21 13:11
Working on it.

**Comment by casper7609** [comment] 2023-09-22 02:06
> Working on it.

Thank you for answer. I downgraded it to 5.2 and it's working.

**Comment by zydeas** [comment] 2023-09-22 04:43
Thanks for attending to this issue.

**Comment by BjornGameDev** [comment] 2023-09-22 10:39
I got it working doing the following changes. 

Instead of pointing directly at the file just added the AssetRegistry namespace: 
#include "AssetRegistry/AssetRegistryModule.h"

File: Plugins\SpinePlugin\Source\SpineEditorPlugin\Private\SpineAtlasImportFactory.cpp

In addition to make it work with Unreal Engine 5.3 I had to add the Body Setup Class to the Skeleton renderer component:
#include "PhysicsEngine/BodySetup.h"

File: Plugins\SpinePlugin\Source\SpinePlugin\Private\SpineSkeletonRendererComponent.cpp

**Comment by BjornGameDev** [comment] 2023-09-22 12:56
> I got it working doing the following changes.
> 
> Instead of pointing directly at the file just added the AssetRegistry namespace: #include "AssetRegistry/AssetRegistryModule.h"
> 
> File: Plugins\SpinePlugin\Source\SpineEditorPlugin\Private\SpineAtlasImportFactory.cpp
> 
> In addition to make it work with Unreal Engine 5.3 I had to add the Body Setup Class to the Skeleton renderer component: #include "PhysicsEngine/BodySetup.h"
> 
> File: Plugins\SpinePlugin\Source\SpinePlugin\Private\SpineSkeletonRendererComponent.cpp

This makes it compile on 5.3, but when importing a skeleton it will just create a Texture folder, but the skeleton data doesn't show up. So now it just silently dies.

**Comment by badlogic** [comment] 2023-09-25 13:27
Still working on this. It's very weird. `USpineSkeletonAssetFactory::FactoryCreateFile` is called upon dropping a file in the content viewer of the UE editor.

<img width="1181" alt="Screenshot 2023-09-25 at 15 22 55" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/4134e621-e014-4e01-a703-8f74327f6c46">

It successfully completes and loads the data as it should. `USpineSkeletonDataAsset::GetAssetRegistryTags` is then also called as expected and returns sensible data.

<img width="1776" alt="Screenshot 2023-09-25 at 15 25 52" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/d9b0aea2-3fb7-4cd9-b032-c99a2b2dd74a">

But no `.uasset` file is created. I do not understand why.

<img width="920" alt="Screenshot 2023-09-25 at 15 27 06" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/0c326806-eecf-4847-ae88-c32349509ace">

The release notes of UE 5.3 do not mention any changes related to this. So I'm a bit at a loss why this has stopped working.

Investigating...

**Comment by badlogic** [comment] 2023-09-25 13:59
If one closes the editor after an import, the editor asks if the asset should get saved. The asset's `Serialize()` method is then called and will write a `.uasset` file to disk.

Upon a restart, the asset will still not show up in the content viewer...

<img width="961" alt="Screenshot 2023-09-25 at 15 59 20" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/b64b12f9-6d6f-4295-9f32-b64c258f5d4a">

**Comment by badlogic** [comment] 2023-09-25 14:02
Same is true for `.atlas` assets. This is mighty confusing.

**Comment by torus** [comment] 2023-09-26 07:54
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/65044/a25c5345-e8d9-41bb-ba88-e1a9ecc97841)
On my project, some very old spine assets are shown on the content browser!
I think these files were exported with Spine 3.x and imported with UE 4.x.

**EDIT**
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/65044/a585a32c-96c9-4d80-80ef-f11c83e15e3f)
At that time, skeleton data and atlas are two separate .uasset files. Maybe that's a major difference?

**Comment by badlogic** [comment] 2023-10-05 09:58
The issue is this:

- Import a file, e.g. owl.atlas
- The `USpineAtlasAssetFactory::FactoryCreateFile()` method is called with an `InName` equal to `owl`
- The method rewrites the `InName` to `owl-atlas` and returns a new `USpineAtlasAsset`
- UE 5.3 content browser no longer displays the imported files, as the `InName` of `owl` is not equal to the object name `owl-atlas`. 

This has worked since UE 4.21 and broke in 5.3. On our end, we have no way to fix this for old assets that have been saved with this convention. This means if you load an old UE project in UE 5.3, those assets will not show up in the content browser!

I've commited a fix to the 4.1 and 4.2-beta spine-runtimes branches, which will not change the `InName` to `<file-atlas` or `<file>-data`. Any newly imported files will thus work as intended and show up in the content browser.

I'll report an issue to UE, but I'm not holding my breath that this will get fixed on the UE side.

**Comment by torus** [comment] 2023-10-12 07:23
Hello @badlogic 

I tried to import a JSON and an atlas files exported with Spine 4.1.23, I got a warning like below:
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/65044/06164b00-224e-4f48-a3f8-fad0415d040b)

Then, only an atlas and texture files are generated and I don't see the skeleton data.
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/65044/b8cff07f-e1fc-4b2b-adf0-17b472f5c0dd)

I'm using UE 5.3.0 and the 4.1 branch of Spine runtime. Did I miss something?

**Comment by badlogic** [comment] 2023-10-12 07:26
I've tested exactly this multiple times in various variations (e.g. only .atlas, .skel, .json) and didn't see this issue.

What OS are you on?

**Comment by torus** [comment] 2023-10-12 07:28
Thanks for the quick reply!
I tried on Windows and Linux.

**Comment by badlogic** [comment] 2023-10-12 07:33
I'll investigate!

**Comment by badlogic** [comment] 2023-10-18 13:43
@torus I can repro now, both .atlas and .skel files have to have the same name for this to happen (e.g. skeleton.atlas and skeleton.json), something that's not the case with our example assets.

I'm afraid there's nothing we can do on the spine-ue4 runtime side to fix this. You'll have to rename your .skel and .atlas files to not have the same name.

**Comment by badlogic** [comment] 2023-10-18 13:45
I've pinpointed the issue in the UE sources. This change in UE 5.3 is responsible for assets no longer showing up:

https://github.com/EpicGames/UnrealEngine/commit/55a1b3af29f17cda173116e7963e807d681240d0#diff-ab300c6b2bc737d46a7efe22894c3eec70c53022a1adfdfc0d8fb3a3d77d69caR1128

Previously, Spine assets were reported as what's called primary assets, and thus show up in the content browser. Due to the above change, that is no longer the case. This is a bug in UE, which I've already tried to report once, but the issue got closed without comment.

The other change responsible for assets not showing up in the content browser or asset picker anymore is here:
https://github.com/EpicGames/UnrealEngine/blame/release/Engine/Plugins/Editor/ContentBrowser/ContentBrowserAssetDataSource/Source/ContentBrowserAssetDataSource/Private/ContentBrowserAssetDataCore.cpp#L147C8-L147C8

`isPrimaryAsset()` no longer returns true for our assets.

I'm currently working on a repro project for the UE team and resubmit in the hopes that they will actually look at it.

**Comment by badlogic** [comment] 2023-10-18 15:51
Found a way to make the UE content browser display the assets again, but now we can't edit them, as the editor thinks they are cooked.

I'm afraid there's no way to fix this on our end. I've reached out to my network to see if I can get in touch with Epic directly about this.

<img width="661" alt="Screenshot 2023-10-18 at 17 48 50" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/2f19dcf9-647f-4967-b31d-ca2997f15b0d">

<img width="758" alt="Screenshot 2023-10-18 at 17 47 49" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/5be3e7b5-01e9-4381-a976-31a10d0b917a">

**Comment by torus** [comment] 2023-10-19 01:24
@badlogic Thank you for the investigation!
Since we are still using Spine 4.0 and we already have lots of imported skeleton/atlas assets, we decided to downgrade the engine to UE5.2.
I'll also check if we can fix the engine on our local build.

**Comment by badlogic** [comment] 2024-01-16 09:35
I'm closing this out, as Epic has been unresponsive after multiple tries to getting in contact with them. I doubt they'll fix this up.

For Unreal Engine 5.3 and above, your atlas and skeleton files need to have different "prefixes". E.g. "skeleton.json" and "skeleton.atlas" will not work. "skeleton-data.json" and "skeleton-atlas.atlas" will.

For existing projects you want to upgrade to UE +5.3 I'm afraid there is no way to automate the upgrade. You will have to rewire all your skeletons manually.

**Closed as completed by badlogic** 2024-01-16 09:35 UTC
Labels: bug

**Comment by zydeas** [comment] 2024-01-16 12:59
@badlogic Thanks for taking your time to investigate this issue, sorry that the attempts to get Epic to deal with this issue were not successful. As long as there's at least some way for me to import skeletons on 5.3, it'll be okay.
