### ISSUE TITLE
[unity] Unity Spine issue when SDK from 3.8-2021-02-22 to 3.8-2021-03-24

### ISSUE THREAD

**Issue by SyaoranChang** [EsotericSoftware/spine-runtimes#1869] opened 2021-03-29 06:46 UTC
Hi,

Unity Spine has issue when SDK from 3.8-2021-02-22 to 3.8-2021-03-24

My project's Spine file some use Json, some use skel (binary).
On spine-unity 3.8-2021-02-22 Work Fine.
![Snipaste_2021-03-29_14-37-07](https://user-images.githubusercontent.com/18550228/112796929-3fd32700-909d-11eb-86df-8ac20f590425.png)

But On spine-unity 3.8-2021-03-24 It seems brekon.

![Snipaste_2021-03-29_14-34-55](https://user-images.githubusercontent.com/18550228/112796976-51b4ca00-909d-11eb-89d5-13c9070670da.png)

**Comment by HaraldCsaszar** [comment] 2021-04-13 13:23
Thanks for reporting! This is a duplicate of issue ticket https://github.com/EsotericSoftware/spine-runtimes/issues/1867
Already fixed on 2021-04-02.

**Closed as completed by HaraldCsaszar** 2021-04-13 13:23 UTC
Labels: bug
