### ISSUE TITLE
[js] Keyframe for IK constraint mix crashes javascript runtime.

### ISSUE THREAD

**Issue by petterhyden** [EsotericSoftware/spine-runtimes#419] opened 2015-05-05 11:21 UTC
Having issues when setting keyframes for IK constraint Mix in the javascript runtime.
Transition seems to be fine, but setting the Mix keyframe causes the whole animation to go "corrupt". No error or message in the console.
Using the latest version from spine-runtimes and 2.1.27 of Spine.

Result from just adding a single Mix keyframe to any of the animations in SpineBoy:
![screen shot 2015-05-05 at 11 44 17](https://cloud.githubusercontent.com/assets/1153342/7471606/6f32a2a4-f329-11e4-9e0c-f7702f931302.png)

**Comment by petterhyden** [comment] 2015-05-27 07:14
Would be nice if somebody could look into this bug, or tell us not to use it if it will not be supported in the javascript runtime.

**Comment by NathanSweet** [comment] 2015-05-27 08:32
Sorry you haven't gotten a response sooner. Unfortunately I am currently on vacation and won't be back until mid-June. IK mix keys should work in spine-js. This bug could be caused by a typo during porting from spine-libgdx. I will look into it as soon as I am back.

**Comment by petterhyden** [comment] 2015-05-27 11:18
:+1:

**Comment by bepper08** [comment] 2015-07-08 13:32
I've lost access to my petterhyden account and unable to recover :'(. If you ever feel like fixing this issue and want to contact me I'm on bepper08 now :)

**Comment by badlogic** [comment] 2016-07-18 13:14
Been a long time, but if you got a sample for us that repros this, I can have a look while updating the spine-js runtime to 3.4.0, see https://github.com/EsotericSoftware/spine-runtimes/issues/613

**Comment by badlogic** [comment] 2016-08-24 20:32
This should be fixed in the new spine-ts runtime.

**Closed by badlogic** 2016-08-24 20:32 UTC
Labels: bug, runtimes
