### ISSUE TITLE
[unity] "Atlas source cannot be null!" error upon jpg import in Unity 2022.2.5f1

### ISSUE THREAD

**Issue by SwingWren** [EsotericSoftware/spine-runtimes#2237] opened 2023-02-07 14:33 UTC
After updating to unity 2022.2.5f1 this warning started popping up on import.
<img width="612" alt="image" src="https://user-images.githubusercontent.com/54956736/217273228-468316b6-3805-44e3-b671-2f880d377f71.png">

Unity 2022.2.5f1
spine-csharp Runtime 4.1.0
spine-unity Runtime 4.1.0

**Comment by HaraldCsaszar** [comment] 2023-02-07 18:08
Unfortunately we could not reproduce this issue. Does this occur on every newly added skeleton assets for you (adding the exported files from the Spine Editor in a folder in the Unity Project panel)? Or does this happen when re-importing an existing project with the new Unity version? If the issue only occurs on existing re-imported assets, it's likely that something went wrong with your `.meta` files, so that e.g. an AtlasAsset has changed its GUID and this us no longer linked properly to the SkeletonDataAsset.

Could you please send us a minimal Unity project that still shows this problem? You can send it as a zip package to contact@esotericsoftware.com, briefly mentioning this issue ticket URL so that we know the context. I'm closing this ticket for now, if we can reproduce the issue, we will be happy to reopen it again.

[Edit: Received reproduction project via mail: FMfcgzGrcXkXRCTPVSFfxZRnlkLBVfdK]

**Closed as completed by HaraldCsaszar** 2023-02-07 18:08 UTC
Labels: bug

**Comment by HaraldCsaszar** [comment] 2023-02-08 19:35
Thanks for sending the reproduction project. We could reproduce the issue and have just committed a bugfix to the 4.1 branch.
It will soon be released as a unitypackage as well.
