### ISSUE TITLE
[ts] PMA with WEBP causes colored borders

### ISSUE THREAD

**Issue by furic** [EsotericSoftware/spine-runtimes#2604] opened 2024-08-19 06:18 UTC
## Description
PMA is working with PNG, but not WEBP. It causes colored borders because the WEBP sprite becomes ["Exported Straight, rendered PMA"](https://esotericsoftware.com/forum/d/3132-premultiplied-alpha-guide/2).

![Scrrenshot](https://i.imgur.com/6uiLyT4.png)

I was working on `spine-pixi` but found out it happens in `spine-canvas` and `spine-player` too, so I assume it happens to all `spine-ts` packages.

WEBP w/o PMA is working as expected.

## Steps to Reproduce
1. Using the spineboy as example, in any package
2. Convert `spineboy-pma.png` to `spineboy-pma.webp` using an [online converter](https://cloudconvert.com/png-to-webp)
3. Update `spineboy-pma.atlas` first line as: `spineboy-pma.webp`
4. (Optional) I also tried exporting WEBP from Spine Editor, with `Premultiply alpha` option enabled, but it causes the same issue

## Expected Behavior

WEBP should work with PMA, just like PNG

## Actual Behavior

Colored borders if WEBP w/ PMA

## Further Investigation

For curiosity, I removed `pma: true` from `spineboy-pma.atlas`, this causes black edges as expected, due to "Exported PMA, rendered Straight". This means the PMA alpha is correct in the WEBP sprite , it is just not getting read correctly (**spine-runtime** problem).

![exported PMA, rendered Straight](https://i.imgur.com/jHPEFPS.png)

Environment:
Spine-Runtime v4.2.58
Mac OS v14.6.1
[Testing branch](https://github.com/EsotericSoftware/spine-runtimes/compare/4.2...furic:spine-runtimes:webp-pma-testing)

**Comment by davidetan** [comment] 2024-08-19 07:15
Thanks for the superdetailed issue :)

However that's to me sounds like a webp compression issue.
If I try to export a 100% quality webp with a graphic software like photoshop, I have no problem at all.

Try to use [Photopea](https://www.photopea.com/) for example. Drag the image and File>Export>WEBP (quality 100%).

**Comment by furic** [comment] 2024-08-19 07:58
Hm... I just tried exporting from Photopea with 100% quality, it "almost fixed" the face but causes issues on other places like the boosters:
![Photopea](https://i.imgur.com/XGlJeF0.png)
Photopea

I also tried using GIMP, with losses export, it is almost good but still has small flaws:
![GIMP](https://i.imgur.com/zgTusu9.png)
GIMP

I reckon WEBP export quality settings shouldn't have any influence on the alpha, just like PNG.

**Comment by davidetan** [comment] 2024-08-19 08:05
I've just tried it too and I see no strange artifacts. This is the wepb pma spineboy texture:
[spineboy-pma.webp.zip](https://github.com/user-attachments/files/16657456/spineboy-pma.webp.zip)

**Comment by furic** [comment] 2024-08-19 08:20
I tried your Webp and it's working. 

I don't have Photoshop installed, but I can spot the size difference and that gotta be something to do with how Webp is exported.

Original PNG: 245kb
Your Photopea WEBP: 223kb
My Photopea WEBP (100% quality): 195kb
GIMP WEBP (lossless): 170kb

[spineboy-pma.zip](https://github.com/user-attachments/files/16657688/spineboy-pma.zip)

**Comment by davidetan** [comment] 2024-08-19 08:26
Actually mine is exported from Photopea, not Photoshop.
If I reduce the quality I see artifacts too.
Clearely, increasing the quality will reduce the compression effect of the webp.

I think we can close the issue since this is not a bug.
Thanks for reporting this because can still be useful for other users in the future.

**Closed as completed by davidetan** 2024-08-19 08:26 UTC

**Comment by furic** [comment] 2024-08-19 08:28
Yup, using a diff tool like P4Merge, I can see that no alpha difference.

But with my WEBPs, it shows difference where the Spine boxes appears.
![diff](https://i.imgur.com/BBrPwRI.png)

**Comment by dvelasquez-dk** [comment] 2024-12-04 01:33
@davidetan does this mean exporting from source as webp using the spine editor is not recommended? Seems strange to require the extra step

**Comment by furic** [comment] 2024-12-04 04:33
Yea unfortunately neither Photopea nor Spine Editor fix this for us, we're just sticking with WEBP w/o PMA for now.

**Comment by davidetan** [comment] 2024-12-04 08:59
@dvelasquez-dk If you don't want artifacts, you should just export your `webp` without any compression. In the Spine editor, if you start with default settings, this should correspond to this:

<img width="606" alt="image" src="https://github.com/user-attachments/assets/a189048b-0d08-48a0-b1a5-90c3c9bedc99">

Clarly, no compression implies no size reduction.

**Comment by davidetan** [comment] 2024-12-04 09:02
@furic Using pma or non pma textures in `spine-pixi` should not make any difference. Non-pma textures are transformed in pma textures during texture creation.

**Comment by dvelasquez-dk** [comment] 2024-12-04 19:10
@davidetan thanks! and yep we turned off alpha compression after our first pass but still getting artifacts with PMA = true, however we are running `spine-threejs`, anything to recommend on that front?

*PNG w PMA working great in `spine-threejs` in 4.2

**Comment by davidetan** [comment] 2024-12-05 08:49
> @davidetan thanks! and yep we turned off alpha compression after our first pass but still getting artifacts with PMA = true, however we are running `spine-threejs`, anything to recommend on that front?
> 
> *PNG w PMA working great in `spine-threejs` in 4.2

I tested it in `spine-threejs` with our examples and no artifacts appear. Are your sure you are also setting: `Quality: Lossless | 100 (Maximum)`
<img width="435" alt="image" src="https://github.com/user-attachments/assets/e00a1982-e7ff-4cf6-9c7a-cbc8a8665a5f">

As a side not, since you use `spine-threejs`, I just want to let you know that we're almost ready to release a new version of it aligned with the latest updates on threejs. Moreover the skeletons will be able to receive light, cast and receive shadows.

**Comment by dvelasquez-dk** [comment] 2024-12-13 20:07
Just to follow up, Quality was not set to Lossless with 100 in our previous exports and correcting it worked! Thanks!

**Comment by davidetan** [comment] 2025-12-04 10:20
For future reference, in 4.3 Editor WebP + PMA will be available only if:

* `Compression` is set to `0 - None (fastest)`
* `Quality` is set to `Lossless`

These two settings are the ones that allow preserving the PMA relation between RGB and A values after WebP compression occurs.

PMA is a preprocessing operation that multiplies each color pixel value by the alpha.
It means that each pixel in the image is passed through this transformation:

```
R -> R * A = r
G -> G * A = g
B -> B * A = b
A ->     A = a
```

In a WebP image, pixels are no longer stored as a “grid”, but closer and similar pixels are stored together, altering their values in order to reduce/compress the data.

So, after decompression, each pixel is slightly different, and the COLOR * A = color relation is no longer exact:

```
r ≃ R * A
g ≃ G * A
b ≃ B * A
a ≃ A
```

This is why there are artifacts with WebP + PMA where A < 1.

Keeping compression at 0 and quality at 100 basically preserves the pixels, and only identical pixels are compressed together.
This implies that the compression advantage is much lower and heavily depends on the image (how many similar pixels there are).
For example, with the `celestial-circus-pro` example, I have:

* PNG with PMA: 4.4 MB
* WebP with PMA (Compression 0, Quality Lossless): 3.2 MB

The advantage is still significant.

However, we can achieve much better results if we instead use non-PMA textures. For example:

* WebP non-PMA (default settings, except Quality: Lossless 100%): 2.5 MB
* WebP non-PMA (default settings, except Quality: Lossy 100%): 1.1 MB
* WebP non-PMA (default settings): 463 KB

With the default settings we get almost a 10x compression factor (you see compression artifacts only if you zoom in a lot in areas with very similar colors).

But as we know, non-PMA textures have problems with blending modes and areas with low alpha (around texture edges). This is not a problem in all runtimes. For example, `spine-pixi` runtimes premultiply textures on upload. This means that using PMA or non-PMA textures makes no difference.

We plan to do this for all TS-based runtimes, starting with `spine-webgl`, which is used by `spine-player`, `spine-webcomponents`, and `spine-phaser`. This change will probably ship with `4.3`.

This change will basically unlock the possibility to use the desired compression level for WebP in all TS-based runtimes.
