### ISSUE TITLE
[c] clearTrack(s) in a complete event callback will re-trigger the complete event for the same entry (and loop forever)

### ISSUE THREAD

**Issue by Fraggle** [EsotericSoftware/spine-runtimes#797] opened 2016-12-07 14:04 UTC
Hello,

The title pretty much explains it all :)
If I get a complete event for one trackEntry and I clearTrack on the trackEntry's trackIndex, I get another complete event for that trackEntry and so on...
I can escape the infinite recursion by checking if the entry is still the current one on the trackIndex but I believe that might be a bug.

Thanks,

Seb

**Comment by NathanSweet** [comment] 2016-12-08 00:01
I cannot reproduce this. `clearTrack` should not be able to fire `complete`.

```
state.setAnimation(0, "walk", true).setListener(new AnimationStateAdapter() {
	public void complete (TrackEntry entry) {
		state.clearTrack(entry.getTrackIndex());
	}
});
```

**Comment by badlogic** [comment] 2016-12-08 10:34
I can't reproduce this either. I've modifed the cocos2d-x example, SpineboyExample.cpp:

```
SkeletonAnimation* s = skeletonNode;
skeletonNode->setCompleteListener( [&, s] (spTrackEntry* entry) {
	log("%d complete", entry->trackIndex);
	s->clearTrack(0);
});
```

And do not see an infinite loop. Could you please modify either the sfml or cocos2d-x sample to demonstrate the issue?

**Comment by badlogic** [comment] 2016-12-14 07:30
Hey @Fraggle, got any more info for us? As said above, we can't repro this in either the reference implementation nor the spine-c runtime.

**Comment by Fraggle** [comment] 2016-12-14 08:50
Hi!

Sorry i didn't get the time to prepare an example for you but I'll.
I forgot to mention the fact that, after clearing the tracks, i set another another anim on track 0.
My situation is more like this:
```
state.setAnimation(0, "walk", false).setListener(new AnimationStateAdapter() {
	public void complete (TrackEntry entry) {
		state.clearTracks();
		state.setAnimation(0, "anotheranim", false);
	}
});
```

**Comment by jpoag** [comment] 2016-12-14 20:38
Repo'd in the unit tests, below the reproduceIssue_loop:

```
static void issue_797_AnimStateHandler(spAnimationState* state, int type, spTrackEntry* entry, spEvent* event)
{
	if (type == SP_ANIMATION_COMPLETE)
	{
		spAnimationState_clearTracks(state);
		spAnimationState_setAnimationByName(state, 0, "walk", false);

		/* // fix from reproduceIssue_loop
		spAnimationState_update(state, 0);
		spAnimationState_apply(state, skeleton);
		//*/
	}
}

void MemoryTestFixture::reproduceIssue_797()
{
	spAtlas* atlas = nullptr;
	spSkeletonData* skeletonData = nullptr;
	spAnimationStateData* stateData = nullptr;
	spAnimationState* state = nullptr;
	skeleton = nullptr;

	//////////////////////////////////////////////////////////////////////////
	// Initialize Animations
	LoadSpineboyExample(atlas, skeletonData, stateData, skeleton, state);

	///////////////////////////////////////////////////////////////////////////

	if (state)
		state->listener = (spAnimationStateListener)&issue_797_AnimStateHandler;

	spAnimationState_setAnimationByName(state, 0, "walk", false);

	// run normal update
	for (int i = 0; i < 50; ++i) {
		const float timeSlice = 1.0f / 60.0f;
		spSkeleton_update(skeleton, timeSlice);
		spAnimationState_update(state, timeSlice);
		spAnimationState_apply(state, skeleton);
	}

	DisposeAll(skeleton, state, stateData, skeletonData, atlas);
}
```

I thought that perhaps this was a duplicate of http://esotericsoftware.com/forum/spine-c-3-5-animation-jerking-7451?p=34657#p34657

But the same solution doesn't fix it.

**Comment by jpoag** [comment] 2016-12-14 20:45
and the fix...
```
void spAnimationState_clearTracks (spAnimationState* self) {
	_spAnimationState* internal = SUB_CAST(_spAnimationState, self);
	int i, n, prevDrain;
	prevDrain = internal->queue->drainDisabled;
	internal->queue->drainDisabled = 1;
	for (i = 0, n = self->tracksCount; i < n; i++)
		spAnimationState_clearTrack(self, i);
	self->tracksCount = 0;
	internal->queue->drainDisabled = prevDrain;
	_spEventQueue_drain(internal->queue);
}
```

**Comment by badlogic** [comment] 2016-12-14 20:48
@nate do we want to disable events on clear track?

**Comment by jpoag** [comment] 2016-12-14 21:00
Also, check `spAnimationState_setEmptyAnimations` for same bug

**Comment by NathanSweet** [comment] 2016-12-14 21:33
I don't think `clearTrack` should skip events.

I still can't repro with the reference impl:
```
state.addListener(new AnimationStateAdapter() {
	public void complete (TrackEntry entry) {
		state.clearTrack(0);
		state.setAnimation(0, "run", false);
	}
});
state.setAnimation(0, "walk", true);
```
To try this, uncomment `ui.animationList.clearListeners();` in SkeletonViewer.java and add this code immediately after. It also doesn't repro with the for loop @jpoag has shown.

A `complete` event is only ever queued in `apply`, which isn't involved at all. If the queue is being drained, it's not possible for the same `complete` event to be fired multiple times. Where exactly is the recursion?

**Comment by nate** [comment] 2016-12-14 21:37
pretty sure you didn't mean @nate

**Comment by jpoag** [comment] 2016-12-14 21:41
I tried to repro a week ago with `spAnimationState_clearTrack` and couldn't.

Today I tried to repro with `spAnimationState_clearTracks` and I caught the bug.

The recursion is as follows:
```
void spAnimationState_clearTracks (spAnimationState* self) {
	_spAnimationState* internal = SUB_CAST(_spAnimationState, self);
	int i, n;
	internal->queue->drainDisabled = 1;
	for (i = 0, n = self->tracksCount; i < n; i++)
		spAnimationState_clearTrack(self, i);
	self->tracksCount = 0;
	internal->queue->drainDisabled = 0;
	_spEventQueue_drain(internal->queue);
}
```
if `spAnimationState_clearTracks ` is called while inside the _spEventQueue_drain, then the drainDisable is reset to 0 and then drained again, even if previously draining.  The previous event was never finished, so it's called again.

**Comment by NathanSweet** [comment] 2016-12-14 21:46
Ahh `clearTracks` plural, sorry I missed that. Your fix is right.

**Comment by jpoag** [comment] 2016-12-14 21:47
This is stylistic, but you could also increment/decrement and avoid the temp variable.

**Comment by NathanSweet** [comment] 2016-12-14 21:49
True. I think the variable is OK since it's just used in 2 places.

**Closed** 2016-12-14 21:49 UTC
Labels: bug, runtimes

**Comment by jpoag** [comment] 2016-12-14 21:51
don't forget to check `spAnimationState_setEmptyAnimations` for the same bug

**Comment by NathanSweet** [comment] 2016-12-14 21:51
Yep, I did two commits because I did indeed forget!

**Comment by badlogic** [comment] 2016-12-15 13:17
Fixed in all runtimes, both `clearTracks` and `setEmptyAnimations`.
