### ISSUE TITLE
[ts][pixi] Adding a child Pixi object in a Slot that follows its transform

### ISSUE THREAD

**Issue by furic** [EsotericSoftware/spine-runtimes#2539] opened 2024-06-04 08:27 UTC
## Why
We want to add a child Pixi object (BitmapText, Sprite, Container, or even another Spine) to a slot of a Spine animation, and follows the transform of the slot when it animates. It is a very common use case and useful for having dynamic information within an animation. For example, UI with dynamic text, a character holding different items, etc.
(Protentially something similar to [BoneFollower](http://esotericsoftware.com/spine-unity-utility-components#BoneFollower) and  [SkeletonUtilityBone](http://esotericsoftware.com/spine-unity-utility-components#SkeletonUtilityBone) in `spine-unity`.)

## How in `pixi-spine`
[Each slot in a Spine is an extension of `Pixi.Container`](https://github.com/pixijs/spine/blob/bda2e19cb28a0df2187451bad8ccc14f1e20da23/packages/base/src/SpineBase.ts#L73), so we can simply add the Pixi object to the slot container:
```
const slotContainer = spine.slotContainers[spine.skeleton.findSlotIndex(slotName)] as PIXI.Container;
slotContainer?.addChild(pixiObject);
```
It works well, where my `pixiObject` simply follows all transform info of its parent slot when it animates.

## How in `spine-runtimes-pixi`
Slots here are not `PIXI.Container` anymore, but the slot meshes are. I can add the `pixiObject` under it and update the its transform with `Ticker` (slot mesh doesn't seem updating its transform from animation):
```
let bone: Bone;
const slot = spine.skeleton.findSlot(slotName);
if (slot) {
	bone = slot.bone;
	const mesh = spine.getMeshForSlot(slot);
	mesh.addChild(pixiObject);
}

PIXI.Ticker.shared.add(() => {
	if (bone) {
		pixiObject.position.set(bone.worldX, bone.worldY);
		pixiObject.scale.set(bone.getWorldScaleX(), bone.getWorldScaleY());
		pixiObject.angle = bone.localToWorldRotation(bone.rotation);
	}
});
```

## Issues
The solution works 90% of the time, but it does have 2 issues:
1. The transform of `pixiObject` is 1 frame behind its slot parent's, due to the fact that the `pixiObject` updated its transform, then the spine animation gets updated.
2. Since the slot and the `pixiObject` are no longer parent-child relationships, the rendering order is not working. E.g. Elements that are on top of the slot are not on top of the `pixiObject`.

	

So, is there a better way to achieve this w/o issues?

**Comment by badlogic** [comment] 2024-06-04 09:30
The `Spine` class itself is a pixi container. However, it currently has no methods to interleave custom objects inside the rendering hierarchy of meshes generated for each slot.

It shouldn't be too hard to add this functionality. The basic approach would be this.

1. Add a methods ala `addSlotObject(slotIndex, pixiObject)` and `removeSlotObject(slotIndex, pixiObject)`to `Spine`.
2. `Spine` keeps an internal list of objects attached to a slot. Their rendering order is the order in which they were added.
3. `Spine.getMeshForSlot()` and `Spine.updateGeometry()` need to be modified so that slot objects and meshes generated for slot attachments are sorted correctly by setting their `zIndex`. Additionally, for slot objects added via `addSlotObject()` their transform needs to be aligned with the slot's bone.

@davidetan want to give this a try?

**Comment by furic** [comment] 2024-06-05 02:19
> The `Spine` class itself is a pixi container. However, it currently has no methods to interleave custom objects inside the rendering hierarchy of meshes generated for each slot.
> 
> It shouldn't be too hard to add this functionality. The basic approach would be this.
> 
>     1. Add a methods ala `addSlotObject(slotIndex, pixiObject)` and `removeSlotObject(slotIndex, pixiObject)`to `Spine`.
> 
>     2. `Spine` keeps an internal list of objects attached to a slot. Their rendering order is the order in which they were added.
> 
>     3. `Spine.getMeshForSlot()` and `Spine.updateGeometry()` need to be modified so that slot objects and meshes generated for slot attachments are sorted correctly by setting their `zIndex`. Additionally, for slot objects added via `addSlotObject()` their transform needs to be aligned with the slot's bone.
> 
> 
> @davidetan want to give this a try?

Yeah it would be nice to have `addSlotObject` in the package to achieve this, instead of doing it outside the package. I may also suggest using `slotName` instead of `slotIndex`: `addSlotObject(slotName, pixiObject)`.

Just note that after `mesh.addChild(pixiObject)`, the child `pixiObject` should be sorted with the `zIndex` of `mesh` which should reflect the draw order, but it seems not the case currently.

Otherwise, if somehow `SlotMesh` (extends `PIXI.Container`) is updating its transform and its `zIndex` is reflecting the draw order, then we can add the Pixi object outside the package, similar to `pixi-spine`'s solution.

**Comment by davidetan** [comment] 2024-06-05 07:04
The pixi object will be sorted respecting the draw order.
We're working on that. It will be probably ready at the end of the day 👍

**Comment by davidetan** [comment] 2024-06-05 14:45
@furic This PR address should address your request :)

You can look at [this example](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-ts/spine-pixi/example/slot-objects.html) to understand its usage.

A `Spine` object has now the ability to attach Pixi `DisplayObject`s to `Slot`s.
You can use the `addSlotObject (slotRef: number | string | Slot, pixiObject: DisplayObject): void` method.
As you asked, you can refer to slots by name, but you can also pass the slot index or the slot instance.

Note that you can add only one DisplayObject per slot and that its transform will be modified by the Spine object.
If you want more control over the added objects, you can add a Container where you will be free to add as many Pixi objects as you want, offset their position, angle, scale, etc.

If you want to remove a display object, just call the `removeSlotObject (slotRef: number | string | Slot, pixiObject?: DisplayObject): void` method.
`pixiObject` is optional. If you pass it, the pixi object will be removed only if it corresponds to the one in the given slot.
Note that the display object is only removed, not destroyed.

Finally, we have a `getSlotObject (slotRef: number | string | Slot): DisplayObject | undefined` that simply returns a pixi object given a slot, if there's any.

Let us know if you think that's ok :)

**Comment by davidetan** [comment] 2024-06-06 06:41
Released in 4.2.45.

**Comment by furic** [comment] 2024-06-06 07:20
@davidetan I've just finished an in-depth test. It's almost perfect but I did encounter 2 issues:
1. `pixiObject` doesn't follow the `alpha` of its parent slot
2. `pixiObject` doesn't get masked if its parent slot is being masked

I can provide my testing Spine, but I think it's pretty straight-forward.

**Comment by davidetan** [comment] 2024-06-06 07:39
Hello @furic and thank you for your feedback.

> pixiObject doesn't follow the alpha of its parent slot

This should be straightforward to implement.

> pixiObject doesn't get masked if its parent slot is being masked

With slot being masked, are you referring to the effect of clipping attachments?
In that case it would be way more harder to implement at first sight.

**Comment by furic** [comment] 2024-06-06 08:14
> Hello @furic and thank you for your feedback.
> 
> > pixiObject doesn't follow the alpha of its parent slot
> 
> This should be straightforward to implement.
> 
> > pixiObject doesn't get masked if its parent slot is being masked
> 
> With slot being masked, are you referring to the effect of clipping attachments? In that case it would be way more harder to implement at first sight.

Yes I did mean clipping attachments.
We reckon 95% of our cases aren't using both slot and clipping mask at the same time. I would say it's good for now but would be nice to have it.

**Comment by davidetan** [comment] 2024-06-06 15:40
Thanks for the clarification. I was able to make an implementation to address the issues you pointed out, but I need to make some additional refinements.
Unfortunately, I won't be able to finish it until next week :(

**Comment by davidetan** [comment] 2024-06-12 12:35
@furic We were able to implement both your requests with this commit: https://github.com/EsotericSoftware/spine-runtimes/commit/61e9be2dcc0beba9e62e43ca04ac0bb2a3c3835a

To enable clippinig/masking on pixi objects added using `addSlotObject`, we had to create a pixi mask with the same shape of the clipping attachment.

Feel free to reopen this issue, if anything does not work as expected.

**Comment by joshsurin-eg** [comment] 2024-06-13 01:58
Hey @davidetan, I'm working with @furic on this one and we've encountered a minor issue with the slots with this latest commit. 

When playing an animation with a `pixiObject` added with `addSlotObject`, the new `pixiObject` that was added plays its setup pose for the first frame of the animation. This causes the object to jump if the slot's setup pose doesn't match the first frame of the animation. 

A workaround fix on Spine editor side is to ensure there is no discrepancy between the setup pose and animation's first frame for the slot, but it's less than ideal especially for more complicated usages.

My first assumption would be that the object updating is 1 frame or tick delayed, causing it to flash the setup pose on the first frame of the animation. Sorry I don't have an example at the moment but if you require one let me know and I'll try whip something up.

Thanks so much for your work on this! 😃

**Comment by furic** [comment] 2024-06-13 03:34
FYI, alpha and clipping are working in the last commit. 👍

**Comment by davidetan** [comment] 2024-06-13 07:15
> Hey @davidetan, I'm working with @furic on this one and we've encountered a minor issue with the slots with this latest commit.
> 
> When playing an animation with a `pixiObject` added with `addSlotObject`, the new `pixiObject` that was added plays its setup pose for the first frame of the animation. This causes the object to jump if the slot's setup pose doesn't match the first frame of the animation.
> 
> A workaround fix on Spine editor side is to ensure there is no discrepancy between the setup pose and animation's first frame for the slot, but it's less than ideal especially for more complicated usages.
> 
> My first assumption would be that the object updating is 1 frame or tick delayed, causing it to flash the setup pose on the first frame of the animation. Sorry I don't have an example at the moment but if you require one let me know and I'll try whip something up.
> 
> Thanks so much for your work on this! 😃

Thanks for reporting this, we'll looking into that!

**Comment by davidetan** [comment] 2024-06-13 08:59
@joshsurin Right now, the pixi object is added right after the call to `addSlotObject`, while its transform is updated in the next render loop.
So, my guess is that the pixi object might be rendered with its transform not yet controlled by the spine object.
However, it's hard to say without a reproduction of the issue, and all my tests did not lead to it.

Can you share a minimal project to reproduce the issue?

**Comment by joshsurin-eg** [comment] 2024-06-14 01:42
I've made a minimal project to reproduce the issue. The setup in spine is simply a bone and a slot with an attachment. I use an 'empty' 1x1 transparent image for the attachment which we will replace with `addSlotObject` at runtime. The setup is the bone is simply at the (0,0) origin. The animation starts with a key that does not match the setup pose (the Y value is higher). 

Here is the setup and animation in Spine editor.

![14-06-2024-11-37-35-Spine-Spine_-_slottest](https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/97fa8209-23be-48ab-a24e-1372de97376c)

When replacing the slot with `addSlotObject`, I am getting the flashing issue on the first frame where it displays the bone's setup pose. I've replaced the slot with a green rope. When I refresh the animation, you will notice very briefly it flashes at the origin and then goes up to start the animation.

https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/b6f0114b-5095-4340-b1f8-8bb83acf1026

It is quite fast and hard to notice, my recorder wouldn't even pick it up until I set it to 60FPS. 

The project files:

```
{
"skeleton": { "hash": "dh5I2oLFNaw", "spine": "4.2.29", "x": -0.5, "y": -0.5, "width": 1, "height": 1 },
"bones": [
	{ "name": "root" },
	{ "name": "empty", "parent": "root" }
],
"slots": [
	{ "name": "empty", "bone": "empty", "attachment": "empty" }
],
"skins": [
	{
		"name": "default",
		"attachments": {
			"empty": {
				"empty": { "width": 1, "height": 1 }
			}
		}
	}
],
"animations": {
	"animation": {
		"slots": {
			"empty": {
				"rgba": [
					{ "color": "ffffff7d" },
					{ "time": 1.3333, "color": "ffffffff" }
				]
			}
		},
		"bones": {
			"empty": {
				"translate": [
					{ "y": 99 },
					{ "time": 1, "y": -34 },
					{ "time": 1.3333 }
				]
			}
		}
	}
}
}
```

```
slottest.png
size:16,16
filter:Linear,Linear
scale:0.3
empty
bounds:2,2,1,1
```
![slottest](https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/879eba47-da45-48fb-9501-3f6e3b329ad7)

**Comment by davidetan** [comment] 2024-06-16 09:29
We found the problem being not connected to this feature, but to a code reorganization in this commit https://github.com/EsotericSoftware/spine-runtimes/commit/e498e96355f9c19f02ff55f4d7e9e19e8172ed5c. We moved the update and apply of the state and the skeleton all together. However, the first time the skeleton is rendered, the state was not yet updated. This is why the first frame was rendered in its setup pose.

With this new commit, we ensure the state update happens always before rendering.

**Comment by joshsurin-eg** [comment] 2024-06-18 04:15
Hi David, we have found another issue with adding a `pixiObject` to a slot via the `addSlotObject` method. The issue is that attachment state and attachment keys are not properly being accounted for at runtime.

For example, if I have a slot with an attachment off in setup pose, I expect it to not render anything if I don't play an animation that turns the attachment on. I expect this to be true even if I add an object with `addSlotObject`. However, objects added with `addSlotObject` appear visible even if the attachment is off in setup pose (or animated with attachment keys in an animation).

Using the same example as above:

```
"slots": [
	{ "name": "empty", "bone": "empty", "attachment": "empty" },
]
```
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/8ea274d5-176a-454f-8d13-09f38a3294b6)


In this scenario I have the attachment on as `empty` in Spine Editor.

If I remove this attachment in setup pose, 

```
"slots": [
	{ "name": "empty", "bone": "empty" },
]
```
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/112670645/634f21db-d725-4d78-b2af-c21e990d41d9)

I have this, and I expect the Spine object to not render the empty slot, unless I turn on the attachment in an animation.

Perhaps it could use `visible` member in Pixi Display Object to render attachment states/keys?

**Comment by davidetan** [comment] 2024-06-18 07:20
I don't think that the visibility of the pixi object added using `addSlotObject` should be connected with the visibility of the attachment.
The pixi object is a child of the slot, not of the attachment. At most, it can be seen as a sibling of all skin placeholders and the attachment of the slot.

A possibility might be to connect the state of the pixi object with the state of the active attachment in the slot, but there might be situations in which a user doesn't want to have this connection.

It's definitely more reasonable that the pixi object in a slot has its state connected to the state of the slot. It is already like that, mostly, but visibility is probably not connected yet.
I'll definitely add this.

Let me know if this is enough. Otherwise, try to explain the use case in which you need to connect the state of the attachment to the one of the pixi object.

**Comment by davidetan** [comment] 2024-06-18 16:35
After an internal discussion, we're considering to connect the visibility of the pixi object added to a slot, to the visibility of the active attachment of the same slot. However, this will be probably activated using an optional parameter.
I suppose the signature will be something like this:
`addSlotObject (slotRef: number | string | Slot, pixiObject: DisplayObject, syncToAttachment?: boolean): void`.

**Comment by joshsurin-eg** [comment] 2024-06-19 00:02
I tend to agree that the added object should be seen as more of a sibling of the slot's attachment rather than a replacement. The way we have been using the slot replacement is mainly to dynamically change sprites or text at runtime, for example for localisation, or a dynamic number. In these cases, we only have one object to replace the slot and the slot's (and attachment's) sole purpose is to act as a placeholder for this new sprite or text object. However I can definitely see why some use cases may have a slot with an attachment, as well as an additional object added, without affecting the existing attachment.

That said, there would be no way to control the visibility of the added object from the animation side except through alpha, which introduces a few complications and potential issues, for example the object would always update and calculate because we simply set the alpha to 0 even if the intended outcome is that it is no longer visible. It also adds additional requirements to set the slot's setup alpha to 0 if we don't want it visible in setup pose, which can further complicate things on the animation side.

Your suggestion of syncing the pixi object's visibility to an attachment is a great idea that allows for all these use cases I've mentioned and would certainly solve all our problems!

**Comment by davidetan** [comment] 2024-06-19 08:14
Before adding the aforementioned feature, I want to be 100% sure that you are also aware of the `beforeUpdateWorldTransforms` and `afterUpdateWorldTransforms` methods in a spine object.

The state of the spine object is updated using this `internalUpdate` method:

```
protected internalUpdate (deltaSeconds?: number): void {
	const delta = deltaSeconds ?? Ticker.shared.deltaMS / 1000;
	this.state.update(delta);
	this.state.apply(this.skeleton);
	this.beforeUpdateWorldTransforms(this);
	this.skeleton.update(delta);
	this.skeleton.updateWorldTransform(Physics.update);
	this.afterUpdateWorldTransforms(this);
}
```

This internal update is done right before rendering. As you can see, before and after the skeleton update, you can inject some custom logic to influence the skeleton or to query the skeleton to influence the world. By default, `beforeUpdateWorldTransforms` and `afterUpdateWorldTransforms` are two noop functions.

In your case, you can achieve the desired result by replacing `afterUpdateWorldTransforms`. For example, you could add these two lines of code:

```
const slot = spineboy.skeleton.findSlot("empty");
spineboy.afterUpdateWorldTransforms = () => pixiObject.visible = Boolean(slot.attachment);
```

What do you think about using one of these two functions to achieve your goal?
Let me know if you think it's too annoying to do that and still prefer having the visibility automatically synced to the slot attachment being active.

**Comment by joshsurin-eg** [comment] 2024-06-20 06:57
The custom `afterUpdateWorldTransforms` function works well and is simple to use! Thank you.

**Comment by davidetan** [comment] 2024-06-20 07:06
> The custom `afterUpdateWorldTransforms` function works well and is simple to use! Thank you.

Cool! Glad to hear that :)
`beforeUpdateWorldTransforms ` and `afterUpdateWorldTransforms` are simple but powerful because they let you modify the world based on the skeleton state and vice versa.

For instance, see in [this example](https://github.com/EsotericSoftware/spine-runtimes/blob/4.2/spine-ts/spine-pixi/example/control-bones-example.html#L99), how simple is to control a bone position based on some external elements.

**Closed as completed by davidetan** 2024-06-20 07:06 UTC
Labels: enhancement

**Comment by davidetan** [comment] 2025-01-09 08:23
We eventually decided to add an option to sync attachment visibility to the slot object. See here the current proposal: https://github.com/EsotericSoftware/spine-runtimes/issues/2731

It will be implemented soon.

**Comment by mcofko** [comment] 2025-08-01 10:44
Hey @davidetan  just read the whole thread, and was really awesome to see that you re-added this functionality to pixi-v7 & pixi-v8 as it's super useful, and can speed up game development tremendously.
I noticed though that this "addSlotObject()" method was only added for pixi game engine. I would like to ask if there's similar functionality also available for Phaser v3 & v4? Can we achieve the same things through a different approach in Phaser?

**Comment by davidetan** [comment] 2025-08-01 11:04
Hello :)

While this feature might seem simple, it's actually quite complex and requires deep integration with the game library.
Spine runtimes for Phaser don't use Phaser's WebGL renderer; instead, they take the WebGL context and use `spine-webgl` under the hood.
Spine runtimes for Pixi, on the other hand, use Pixi’s own renderer. This means that when we draw a Spine attachment or mesh, we can place a Pixi GameObject before drawing another one.

One of my tasks was to use [Phaser Meshes](https://docs.phaser.io/phaser/concepts/gameobjects/mesh) to reach a similar level of integration with Phaser. This would have also enabled many Phaser features that you currently can't use with a Spine GameObject.

However, in Phaser 4, meshes have been removed. This makes it much harder to achieve the level of integration required to implement an `addSlotObject()` feature.
I'm not even sure this would be possible at all without using a mesh object from Phaser.

Rather than an `addSlotObject()` feature in Phaser in the near future, it's more likely that we’ll focus on [this feature instead](https://github.com/EsotericSoftware/spine-runtimes/issues/2639).
It allows you to easily swap a texture on an attachment or mesh. So instead of placing a GameObject in a slot, you’d replace or add a texture to it.

If you’d like to continue the discussion, please open a new issue and link to this one.
