### ISSUE TITLE
[runtimes] IK is acting weirdly with this one skeleton.

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#866] opened 2017-03-23 08:00 UTC
User "jsa316" sent a repro case of IK misbehaving in the runtimes but not in the editor.
http://esotericsoftware.com/forum/Spine-Unity-bug-8010

This doesn't seem to be showing up in any of our test/example skeletons.
But it's not specific to spine-unity. I've tried viewing OP's repro skeleton in http://esotericsoftware.com/spine-skeleton-viewer and the problem is visible there too, but not in Spine Editor.

Needs further checking.
What we know so far:
- It's **not specific to spine-unity**. This weird behavior is confirmed with Spine-Unity and Spine Skeleton Viewer.
- video of it glitching from OP. This is confirmed. : https://www.dropbox.com/s/y79p8sun67i36sn/Idle.avi?dl=0
- Checked if it's a superficial serialization problem, but loading the json back into Spine doesn't seem to cause it to show in the Spine editor. Not sure if that's conclusive.

**Comment by badlogic** [comment] 2017-03-23 10:29
Can be reproduced in 3.6-beta editor as well, though the glitch is nowhere as appearant as in the video. It appears the IK solution isn't stable, meaning, the bone at the end of the chain is actually not properly pointing at the IK target. Might be that we don't see it in our samples as the repro case here has a very long bone pointing at the target, so small rotational errors result in large deviations.

The fun part is that the IKConstraint code hasn't changed since October. I keep digging.

**Comment by badlogic** [comment] 2017-03-23 10:34
Moved to `master` build of editor, using `master` runtime, same issue. Something has changed in the runtime since the last 3.5.51 release, question is what.

**Comment by badlogic** [comment] 2017-03-23 13:07
Riddle solved...

The spine-libgdx runtime uses `MathUtils` from libGDX for trigonometric functions ala cos, sin, atan2. That class uses lookup tables internally. The same is true for spine-csharp. When running the problematic project via spine-ts or spine-c, the issues disappear, as they use run of the mill trig functions provided by the language runtime.

For the problematic project, the precision of those LUTs is insufficient.

I suggest we get rid of all LUT code. They aren't faster on the JVM, Dalvik, ART or Mono and lead to precision issues that cost me a day to figure out.

**Comment by badlogic** [comment] 2017-03-24 14:15
Fixed in reference implementation and spine-unity. All other runtimes do not use LUTs.

**Closed by badlogic** 2017-03-24 14:15 UTC
Labels: bug, runtimes
