### ISSUE TITLE
[unity]  import 3.8.95 Binary Data  ERROR

### ISSUE THREAD

**Issue by jeffxby** [EsotericSoftware/spine-runtimes#1679] opened 2020-05-18 09:37 UTC
Binary Data Form 3.8.95 Editor ,import  to unity throw error when read audio Path Data, then I try  open the nonessential selection, import  again it  .throw error in read Slots Data.   change to json data it work.

**Comment by HaraldCsaszar** [comment] 2020-05-19 19:04
Unfortunately we could not reproduce the problem. Could you please send us your problematic assets as a zip package, either to contact@esotericsoftware.com or attached to this ticket? Then we can have a look at it.

Closing the ticket for now. We will happily reopen when the assets are available.

**Closed as completed by HaraldCsaszar** 2020-05-19 19:04 UTC
Labels: bug
