### ISSUE TITLE
[lua][corona] multi-page atlas error

### ISSUE THREAD

**Issue by BlytzStyle** [EsotericSoftware/spine-runtimes#729] opened 2016-10-14 12:48 UTC
skeleton1.png
skeleton2.png

skeleton.atlas

Attempt to perform arithmetic on local 'x' (a nil value)

File: spine-lua/TextureAtlas.lua
Line: 192

stack traceback:
	spine-lua/TextureAtlas.lua:192: in function 'parse'
	spine-lua/TextureAtlas.lua:68: in function 'new'
	main.lua:19: in function 'loadSkeleton'

Can someone help me with this error? 

Everything I write in this website is translated from Italian into English by Google. I apologize if you do not understand.

**Comment by badlogic** [comment] 2016-10-17 12:21
I tested multi-page atlases and they work as intended. Make sure you used Spine 3.4.02 to export your atlas. Please post your .json and .atlas files so i can reproduce the error.

**Comment by BlytzStyle** [comment] 2016-10-17 13:05
If you need png and give me a mail and you send them.

If you create a single png it s ok,  but I have a fault, I think zero scale objects early animation producing this type of error.

Thanks for the help!

[Archive.zip](https://github.com/EsotericSoftware/spine-runtimes/files/533476/Archive.zip)

**Comment by badlogic** [comment] 2016-10-20 11:23
Yes, please send the pngs to contact@esotericsoftware.com!

**Comment by badlogic** [comment] 2016-10-20 12:33
This should be fixed now, there was an error in the texture atlas parser. Thanks for reporting!

**Closed** 2016-10-20 12:33 UTC
Labels: bug, runtimes
