### ISSUE TITLE
[ue4]Spine crashed when startup on iOS

### ISSUE THREAD

**Issue by jashking** [EsotericSoftware/spine-runtimes#1475] opened 2019-09-02 14:39 UTC
UE: 4.18
Spine: 3.8
![code](https://user-images.githubusercontent.com/2841098/64121812-6ef6b900-cdd2-11e9-9146-cc89a73c4e37.png)
![info](https://user-images.githubusercontent.com/2841098/64121813-6f8f4f80-cdd2-11e9-9c43-b51cbb388089.png)
![stack1](https://user-images.githubusercontent.com/2841098/64121814-6f8f4f80-cdd2-11e9-878c-764a81736024.png)

**Comment by badlogic** [comment] 2019-09-02 18:28
How can I reproduce this?

**Comment by jashking** [comment] 2019-09-03 06:35
Hi，I use spine::String instead of std::string in RTTI class, and problem solved
```cpp
namespace spine {
class SP_API RTTI : public SpineObject {
public:
	explicit RTTI(const char* className);

	RTTI(const char* className, const RTTI &baseRTTI);

	const String &getClassName() const;

	bool isExactly(const RTTI &rtti) const;

	bool instanceOf(const RTTI &rtti) const;

private:
	// Prevent copying
	RTTI(const RTTI &obj);

	RTTI &operator=(const RTTI &obj);

	const String _className;
	const RTTI *_pBaseRTTI;
};
}
```

**Comment by badlogic** [comment] 2019-09-16 13:57
I have tried this with UE 4.20-4.23 on both macOS and iOS and couldn't see the crash you reported using a few different default scenes (though the crash happens when the plugin is initialized, so the scene shouldn't matter). It might be an issue with 4.18 which we no longer support going forward. Since you've found a work around for yourself, I'm closing this out.

**Closed as completed by badlogic** 2019-09-16 13:57 UTC
Labels: bug
