### ISSUE TITLE
[cocos2d-x] SkeletonRenderer color render is wrong

### ISSUE THREAD

**Issue by lsc1414** [EsotericSoftware/spine-runtimes#580] opened 2016-05-20 13:21 UTC
When I set a color(eg:FAFCFFFF) to attachment in setup mode,The color displayed was wrong in cocos2d-x。
But If the color is FFFFFFFF ,the color displayed was right.

the code in SkeletonRenderer.cpp has some mistake:
```c++
void SkeletonRenderer::draw (Renderer* renderer, const Mat4& transform, uint32_t transformFlags) {
	SkeletonBatch* batch = SkeletonBatch::getInstance();

	Color3B nodeColor = getColor();
	_skeleton->r = nodeColor.r / (float)255;
	_skeleton->g = nodeColor.g / (float)255;
	_skeleton->b = nodeColor.b / (float)255;
	_skeleton->a = getDisplayedOpacity() / (float)255;

	Color4B color;
	int vertexCount = 0;
	AttachmentVertices* attachmentVertices = nullptr;
	for (int i = 0, n = _skeleton->slotsCount; i < n; ++i) {
		spSlot* slot = _skeleton->drawOrder[i];
		if (!slot->attachment) continue;

		switch (slot->attachment->type) {
		case SP_ATTACHMENT_REGION: {
			spRegionAttachment* attachment = (spRegionAttachment*)slot->attachment;
			spRegionAttachment_computeWorldVertices(attachment, slot->bone, _worldVertices);
			attachmentVertices = getAttachmentVertices(attachment);
			color.r = attachment->r;
			color.g = attachment->g;
			color.b = attachment->b;
			color.a = attachment->a;
			break;
		}
		case SP_ATTACHMENT_MESH: {
			spMeshAttachment* attachment = (spMeshAttachment*)slot->attachment;
			spMeshAttachment_computeWorldVertices(attachment, slot, _worldVertices);
			attachmentVertices = getAttachmentVertices(attachment);
			color.r = attachment->r;
			color.g = attachment->g;
			color.b = attachment->b;
			color.a = attachment->a;
			break;
		}
		case SP_ATTACHMENT_WEIGHTED_MESH: {
			spWeightedMeshAttachment* attachment = (spWeightedMeshAttachment*)slot->attachment;
			spWeightedMeshAttachment_computeWorldVertices(attachment, slot, _worldVertices);
			attachmentVertices = getAttachmentVertices(attachment);
			color.r = attachment->r;
			color.g = attachment->g;
			color.b = attachment->b;
			color.a = attachment->a;
			break;
		}
		default:
			continue;
		}

		color.a *= _skeleton->a * slot->a * 255;
		float multiplier = _premultipliedAlpha ? color.a : 255;
		color.r *= _skeleton->r * slot->r * multiplier;
		color.g *= _skeleton->g * slot->g * multiplier;
		color.b *= _skeleton->b * slot->b * multiplier;

		for (int v = 0, w = 0, vn = attachmentVertices->_triangles->vertCount; v < vn; ++v, w += 2) {
			V3F_C4B_T2F* vertex = attachmentVertices->_triangles->verts + v;
			vertex->vertices.x = _worldVertices[w];
			vertex->vertices.y = _worldVertices[w + 1];
			vertex->colors = color;
		}

		BlendFunc blendFunc;
		switch (slot->data->blendMode) {
		case SP_BLEND_MODE_ADDITIVE:
			blendFunc.src = _premultipliedAlpha ? GL_ONE : GL_SRC_ALPHA;
			blendFunc.dst = GL_ONE;
			break;
		case SP_BLEND_MODE_MULTIPLY:
			blendFunc.src = GL_DST_COLOR;
			blendFunc.dst = GL_ONE_MINUS_SRC_ALPHA;
			break;
		case SP_BLEND_MODE_SCREEN:
			blendFunc.src = GL_ONE;
			blendFunc.dst = GL_ONE_MINUS_SRC_COLOR;
			break;
		default:
			blendFunc.src = _premultipliedAlpha ? GL_ONE : GL_SRC_ALPHA;
			blendFunc.dst = GL_ONE_MINUS_SRC_ALPHA;
		}

		batch->addCommand(renderer, _globalZOrder, attachmentVertices->_texture->getName(), _glProgramState, blendFunc,
			*attachmentVertices->_triangles, transform, transformFlags);
	}

	if (_debugSlots || _debugBones) {
		_debugCommand.init(_globalZOrder);
		_debugCommand.func = CC_CALLBACK_0(SkeletonRenderer::drawDebug, this, transform, transformFlags);
		renderer->addCommand(&_debugCommand);
	}
}
```

the color r,g,b,a  in attachment was a Float type, but r,g,b,a in Color4B was a Byte type.
```c++
			color.r = attachment->r;
			color.g = attachment->g;
			color.b = attachment->b;
			color.a = attachment->a;
```
@NathanSweet

**Comment by badlogic** [comment] 2016-08-01 10:13
This should be fixed, tested with keyed color attachment change in spineboy test animation.

**Comment by lsc1414** [comment] 2016-08-02 06:50
Please Test like this.change region color in setup mode
![1](https://cloud.githubusercontent.com/assets/5005412/17319409/f9dd3368-58bf-11e6-8733-5d5dffdf9bf6.png)
![2](https://cloud.githubusercontent.com/assets/5005412/17319408/f99f6dd0-58bf-11e6-919f-35a7b38e9073.png)

**Comment by badlogic** [comment] 2016-08-02 08:24
You are correct, sorry. It appears that keying color works as intended, but setting the region key doesn't. Fixing.

**Closed** 2016-08-02 08:43 UTC
Labels: bug, in progress, runtimes
