### ISSUE TITLE
[unity] When there are many instances of the same character, draw order becomes glitchy

### ISSUE THREAD

**Issue by chanon** [EsotericSoftware/spine-runtimes#1460] opened 2019-08-20 15:32 UTC
I am using: 
- spine-unity 3.8 2019-08-20
- Spine version 3.8.61 Professional
- SkeletonAnimation

Whenever there is more than 1 character using the same skin in a scene, it becomes glitchy. Body parts go missing and when animated seem to blink.

![image](https://user-images.githubusercontent.com/357737/63361306-12d77200-c39a-11e9-98d4-29a14509f06f.png)

In the image above, all of the characters are exactly the same, they should all look like the first character, but the other 3 for some unknown reason have their eyes missing and the draw order is wrong.

This skeleton is using Spine's new "skin bones" feature. 

No animation has to actually be played. Just duplicating (Ctrl-D) the character and the eyes will disappear in the Scene editor view.

I have found that if I delete skins so there are less skins in the file, it no longer happens. 

Also, it seems to happen depending on the amount of skins in the spine file. If there are about 7 skins, it happens within 3-4 duplicate characters. If I delete one more skin, then I need to duplicate about 6 characters in order for it to happen.

Thinking about it, it is probably a bug related to draw order. The missing eyes are probably being drawn over by the head. There are no animations running to affect the draw order and it is still happening though. So something about lots of skins is affecting keeping track of the draw order when there are many instances of the same skeleton/skin.

Update: It looks like it is related to the number of texture atlases.
If I expand my maximum atlas texture size to 2048 when exporting, so that everything fits into one texture, then it seems to no longer happen.

When there are 2 atlas textures though, it seems that the parts that are in the second atlas start to disappear. Also, I find the number of duplicate materials in the Mesh Renderer strange (but it might be normal)

![image](https://user-images.githubusercontent.com/357737/63362349-e0c70f80-c39b-11e9-8dd3-2c118cfa3a00.png)

**See reproduction Unity project files below**

**Comment by chanon** [comment] 2019-08-20 15:49
So, in summary, (from my understanding) when a character skin uses images from more than one atlas, and that character is duplicated a few times, then the draw order begins to go wrong.

In my case, I have been able to workaround by changing my export texture packer settings.

**Comment by chanon** [comment] 2019-08-20 16:01
OK, here is reproduction using spineboy
![image](https://user-images.githubusercontent.com/357737/63363716-4f0cd180-c39e-11e9-8c17-46e1a83ffc15.png)

[UnityProject.zip](https://github.com/EsotericSoftware/spine-runtimes/files/3521525/UnityProject.zip)

I just force it to 512x512 max texture atlas size so the character uses multiple texture atlases. Then just create and duplicate the SkeletonAnimation instance.

**Comment by HaraldCsaszar** [comment] 2019-08-21 15:35
Thanks for the issue report and reproduction description!

**Comment by HaraldCsaszar** [comment] 2019-08-21 16:25
Reproduced with UnityProject.zip as posted above in Unity 2017.1:
https://github.com/EsotericSoftware/spine-runtimes/files/3521525/UnityProject.zip
Behaves the same when batching is disabled.

Seems to happen only when camera is set to Orthographic. Draw order is correct when changing camera to mode `Perspective`.

**Comment by HaraldCsaszar** [comment] 2019-08-21 16:39
Rotating the camera by a tiny ammount seems to solve the issue - simply set the camera's transform rotation Y value to e.g. `0.001`.

**Comment by HaraldCsaszar** [comment] 2019-08-22 14:55
Unfortunately, neither can submeshes receive separate bounds, nor is Z position respected - 
Unity declares random submesh draw order for orthographic camera to be `By Design` in this issue ticket:
https://issuetracker.unity3d.com/issues/orthographic-camera-ignores-submeshes-render-order

Therefore closing the ticket, proposing two working solutions:
a) Add a `SortingGroup` component at each skeleton GameObject.
b) Rotating the camera by a tiny ammount seems to solve the issue - simply set the camera's transform rotation Y value to e.g. 0.001.

**Closed as completed by HaraldCsaszar** 2019-08-22 14:55 UTC
Labels: bug

**Comment by PatoliStudio** [comment] 2025-03-30 18:32
This is still happening on Unity 2022.3.38f1 and neither of the two options seem to be working for us
