### ISSUE TITLE
[unity] SkeletonRenderTexture incorrect if screen resolution exceeds RenderTexture resolution

### ISSUE THREAD

**Issue by havudk** [EsotericSoftware/spine-runtimes#2180] opened 2022-10-17 07:46 UTC
Hi, 
Thanks for your hard work.
About SkeletonRenderTexture, it working well when Spine not have Skin.
but when I set a Skin to spine, it become very weird.
You can refer with image below
![merge](https://user-images.githubusercontent.com/39358898/196118682-38f04e7f-d7fc-4031-b36b-8272c645c3c2.jpg)

**Comment by HaraldCsaszar** [comment] 2022-10-17 14:35
Closing this issue temporarily since we could not reproduce this issue following your screenshots alone. Could you please send us a minimal Unity reproduction project that still shows this issue? You can send it as a zip package to contact@esotericsoftware.com (briefly mention this issue ticket URL so that we know the context) or attach a link to this ticket. Then we're happy to reopen this ticket and fix any issues.

**Comment by havudk** [comment] 2022-10-19 09:11
@HaraldCsaszar Sorry because contact you here.
I sent to you via email, did you receive and confirm this bug?
Thanks very much.

**Comment by HaraldCsaszar** [comment] 2022-10-19 11:14
Thanks for sending the reproduction project. We were now able to reproduce the problem.

It happens independent of aspect ratio, but when screen resolution (Game preview resolution), e.g. 1920x1080, exceeds `Max Render Texture Size`, e.g. 1024 by default. As a quick fix, for now please just increase `Max Render Texture Size` at the `SkeletonRenderTexture` component to e.g. 2048.

**Comment by havudk** [comment] 2022-10-21 09:32
Thanks very much, I can fixed it...
But I discovered a new bug. 
I run well in iOS but in Android it showed nothing, even in my game so weird when it had a black background in Render Texture
Do you have any idea why this happening?

![3](https://user-images.githubusercontent.com/39358898/197164367-45e7d995-abf5-48d7-b071-149e24bf259b.jpg)
![Android](https://user-images.githubusercontent.com/39358898/197164382-08815494-81cd-4dd0-b295-a05c2ef7632f.png)
![iOS](https://user-images.githubusercontent.com/39358898/197164390-9fa0b934-0b1b-4235-ba1b-c82bdd67b346.PNG)


Thanks

**Comment by havudk** [comment] 2022-10-24 22:21
> Thanks very much, I can fixed it... But I discovered a new bug. I run well in iOS but in Android it showed nothing, even in my game so weird when it had a black background in Render Texture Do you have any idea why this happening?
> 
> ![3](https://user-images.githubusercontent.com/39358898/197164367-45e7d995-abf5-48d7-b071-149e24bf259b.jpg) ![Android](https://user-images.githubusercontent.com/39358898/197164382-08815494-81cd-4dd0-b295-a05c2ef7632f.png) ![iOS](https://user-images.githubusercontent.com/39358898/197164390-9fa0b934-0b1b-4235-ba1b-c82bdd67b346.PNG)
> 
> Thanks

@HaraldCsaszar Hi, do I need to create new issue for this bug?

**Comment by HaraldCsaszar** [comment] 2022-10-28 14:16
Resolved the original issue via commit 661796d.

**Closed as completed by HaraldCsaszar** 2022-10-28 14:16 UTC

**Comment by HaraldCsaszar** [comment] 2022-10-28 14:19
The original issue was resolved on the 4.1 branch. `SkeletonRenderTexture` and `SkeletonGraphicRenderTexture` components now support automatic down-scaling when required size on screen exceeds `Max Render Texture Size`.

A new 4.1 spine-unity unitypackage is available for download:
http://esotericsoftware.com/spine-unity-download

**Comment by HaraldCsaszar** [comment] 2022-10-28 14:21
@havudk Please test whether the above new unitypackage perhaps resolves your issue regarding Android. Perhaps you are running into a render texture size limit, try to keep the render texture size as low as possible.

If the problem persists, please open a new issue ticket.
