### ISSUE TITLE
`gl.getParameter(gl.VERSION).indexOf("WebGL 1.0") != -1;` causing error on Edge v128

### ISSUE THREAD

**Issue by RaenonX** [EsotericSoftware/spine-runtimes#2616] opened 2024-08-29 10:06 UTC
https://github.com/EsotericSoftware/spine-runtimes/blob/d769c1a9308799f529428531606ec7932e6e4316/spine-ts/spine-player/src/Player.ts#L458

This line on my browser is causing the following error:
![image](https://github.com/user-attachments/assets/f4ea364e-00e3-4e1b-8b50-388546636417)

Browser:
```
Microsoft Edge Version 128.0.2739.42 (Official build) (64-bit)
```

Let me know what else do I need to provide. Thanks!

**Comment by davidetan** [comment] 2024-08-29 10:46
I'm on Mac, just installed Microsoft Edge Version 128.0.2739.42 (Official build) (arm64), and it works as expected.

I suppose that the only way `gl.getParameter(gl.VERSION)` return `null` is when the webgl context is lost.

If there is no webgl context at the beginning, you should see the following error in your page in the canvas:
```
Sorry, your browser does not support WebG, or you have disabled WebGL in your browser settings.
Please use the latest version of Firefox, Chrome, Edge, or Safari.
```

If the webgl context is lost after, you should see a sad face like this one:
<img width="42" alt="image" src="https://github.com/user-attachments/assets/c060e900-a214-4cd1-b4db-f8fb734c7b1f">


What do you see in the canvas?

**Comment by RaenonX** [comment] 2024-08-29 11:00
> I'm on Mac, just installed Microsoft Edge Version 128.0.2739.42 (Official build) (arm64), and it works as expected.
> 
> I suppose that the only way `gl.getParameter(gl.VERSION)` return `null` is when the webgl context is lost.
> 
> If there is no webgl context at the beginning, you should see the following error in your page in the canvas:
> 
> ```
> Sorry, your browser does not support WebG, or you have disabled WebGL in your browser settings.
> Please use the latest version of Firefox, Chrome, Edge, or Safari.
> ```
> 
> If the webgl context is lost after, you should see a sad face like this one: <img alt="image" width="42" src="https://private-user-images.githubusercontent.com/7047501/362649103-c060e900-a214-4cd1-b4db-f8fb734c7b1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5Mjg4ODcsIm5iZiI6MTcyNDkyODU4NywicGF0aCI6Ii83MDQ3NTAxLzM2MjY0OTEwMy1jMDYwZTkwMC1hMjE0LTRjZDEtYjRkYi1mOGZiNzM0YzdiMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMTA0OTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGM3YjhlZTJmMDk0NDYyNjQ3YzdkYmJlYTg0OWI0NzQ1NzY0N2UzNjFlMzljM2NmNjk2MDMxNDM1NWNiODc3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aurXPrzwfO7sQ47THBWWejWlJTHUJKSPXmMeltmP8WY">
> 
> What do you see in the canvas?

Thanks for responding. This is what I am seeing:
![image](https://github.com/user-attachments/assets/9fe64837-fbb5-4eba-b2d0-65b8a7a9b5c8)

For more context, I am using React. This is how I initialize it with `hrefOfSkeleton` being the relative link to the skeleton file `/actions/pokemon/regular/194/action/move.skel`; `target` being a ref to a `<div/>` for showing the animation, and `player` being a ref to store the `SpinePlayer` instance.
```typescript
React.useEffect(() => {
  if (!hrefOfSkeleton || !target.current) {
    return;
  }

  player.current = new SpinePlayer(target.current, {
    preserveDrawingBuffer: false,
    skeleton: hrefOfSkeleton,
    atlasUrl: hrefOfSkeleton.replaceAll('.skel', '.atlas'),  // Temporary, file would exist
  });

  return () => player.current?.dispose();
}, [hrefOfSkeleton, target.current]);
```

The callback in `useEffect()` gets called multiple times because of React strict mode.

-----------

In addition, I would like to know if this is a right place to ask https://en.esotericsoftware.com/forum/d/26766-unable-to-load-spine-fils-using-spine-web-player since I am having this issue if I change the line to `gl.getParameter(gl.VERSION)?.indexOf("WebGL 1.0")` to let it pass.

**Comment by davidetan** [comment] 2024-08-29 11:11
As you can see from the warning in your browser console, you are losing your webgl context.

Strict mode during development triggers effects twice. The `Too many active WebGL contexts` warning indicates that your effect is executed multiple time, not only two.

You should fix your effect to be idempotent and initialize the SpinePlayer once.


I'll close this since it's not a bug. We can continue the discussion on the thread you created in the forum.

**Closed as completed by davidetan** 2024-08-29 11:11 UTC

**Comment by RaenonX** [comment] 2024-08-29 11:14
> As you can see from the warning in your browser console, you are losing your webgl context.
> 
> Strict mode during development triggers effects twice. The `Too many active WebGL contexts` warning indicates that your effect is executed multiple time, not only two.
> 
> You should fix your effect to be idempotent and initialize the SpinePlayer once.
> 
> I'll close this since it's not a bug. We can continue the discussion on the thread you created in the forum.

Will continue there, thanks!
