### ISSUE TITLE
[Phaser] autodetect PMA not working

### ISSUE THREAD

**Issue by spayton** [EsotericSoftware/spine-runtimes#2330] opened 2023-08-02 11:21 UTC
Maybe not just for Phaser, but thats what I'm using.  And maybe the runtime is right with a problem in the spine export.

I've noticed that the PMA autodetect isn't working on my spine exports because the text generated in the .atlas isn't exactly what the runtime code is looking for.

In the runtime SpinePlugin.ts/addToCache(), it's looking for an exact match of the string with "pma: true", but in my .atlas it's "pma:true", there's a space character missing, so no match.

The spine version is 4.1.23 pro, running on win10 and set to exportJSON as version 4.1

I've compared my .atlas's with the runtime example assets and there's some differences, not just the missing space character.

Also something else I've noticed that may be relevant, is when saving my JSON export settings to a file - when set to v4.0, this version appears in the json file as "version": 4.0, but when I set to 4.1, the json file now reports it as, "version": null

**Comment by misaki-eymard** [comment] 2023-08-04 00:54
I'm sorry to hear you're having trouble.

> Also something else I've noticed that may be relevant, is when saving my JSON export settings to a file - when set to v4.0, this version appears in the json file as "version": 4.0, but when I set to 4.1, the json file now reports it as, "version": null

Unfortunately, I was not able to reproduce the issue where the file is exported with "version:null". Could you please send your files to us via email?: contact@esotericsoftware.com

**Comment by misaki-eymard** [comment] 2023-08-05 00:06
Thank you for sending the video and your export.json file! I apologize that I misunderstood what you meant at first. It is correct that the version is null in the JSON of the export configuration when you choose "4.1" in the "Version" option of the export dialog. This is because exporting from the 4.1 editor to the 4.1 format is the default behavior and does not need to be changed to another version based on the export.json file. Only when another version is specified, such as 4.0 or 3.8, will that version number be stored in this "version" attribute to apply the setting.

**Comment by badlogic** [comment] 2023-08-06 01:11
@spayton this is now fixed in the 4.1.37 and 4.2.18 releases on NPM.

**Closed as completed by badlogic** 2023-08-06 01:11 UTC
