### ISSUE TITLE
changing skins doesn't change skins

### ISSUE THREAD

**Issue by geddski** [EsotericSoftware/spine-runtimes#863] opened 2017-03-21 22:19 UTC
Using Widget. I change a skin using the API `widget.skeleton.setSkinByName('Bones')` and only a single attachment changes - the character's jaw. When I change skins in Spine editor it changes out the complete skin. I'm guessing the reason the jaw shows up and nothing else is because that's the only slot with the exact same name in both skins. I would expect changing skins to change out all the attachments just like spine editor does. What am I missing?

**Comment by badlogic** [comment] 2017-03-22 11:21
Are you also calling `skeleton.setSlotsToSetupPose()` after you set the skin by name?

This demo here shows how to do randomized skins as well as how to set a specific skin https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-ts/webgl/demos/skins.js

I'm closing this out as it's not a bug, but rather a question about the API. We can continue discussing your problem here. Going forward, could you please post API questions on the forum? That makes it easier for other users to find answers as well. Thanks!

**Closed by badlogic** 2017-03-22 11:21 UTC

**Comment by geddski** [comment] 2017-03-22 17:23
@badlogic yep that did the trick. Sorry, I thought it was a bug. I'll be sure to post questions to the forum instead of here.

**Comment by badlogic** [comment] 2017-03-22 17:23
No worries! We have some plans for making skins at runtime easier to use. Calling `skeleton.setSlotsToSetupPose()` is not super intuitive.
