### ISSUE TITLE
[c] Scale Problem after 4.2 Upgrade

### ISSUE THREAD

**Issue by pinguin999** [EsotericSoftware/spine-runtimes#2509] opened 2024-04-27 10:37 UTC
Hi I stared upgrading [ALPACA](https://github.com/pinguin999/ALPACA) to Spine 4.2. Most things are working but the speech bubbles (A 9 Patch made via Spine) looks wrong after the update.

The Spine file can be found here: 
https://github.com/pinguin999/ALPACA/tree/main/data-src/speechbubble

Images: In Spine and in game 4.1 and 4.2 and the export diff

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/1874603/b1c6ab98-ce47-44b4-8f1e-199aed679608)
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/1874603/41f7dbb9-9ce3-4141-b358-5409f8c381de)
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/1874603/72ee3207-194f-4af2-aa47-0208cc71f18d)
![image](https://github.com/EsotericSoftware/spine-runtimes/assets/1874603/f1ae375e-8541-460f-9120-ceb3c051ca4c)

Code Diff: https://github.com/pinguin999/ALPACA/compare/main...spine4_2

Runtime information
c-runtime 4.2

**Comment by badlogic** [comment] 2024-04-30 08:30
@pinguin999 I've taken the speechbubble.spine project from your repo. Exported it with Spine Editor 4.2.08.  Here are my exports:

[speechbubble.zip](https://github.com/EsotericSoftware/spine-runtimes/files/15160503/speechbubble.zip)

I then loaded those with spine-sfml, which is based on spine-c. They display correctly, both .json and .skel.

<img width="640" alt="Screenshot 2024-04-30 at 10 27 01" src="https://github.com/EsotericSoftware/spine-runtimes/assets/514052/38fec86d-117f-4c74-90b1-0882f46309da">

Your code changes look correct. Since you include the `spine-runtimes` repo as a submodule, I'd also guess that you've fully updated to the latest spine-c sources.

I'm afraid since I can't reproduce the issue with spine-c, I can't really help fix this. Could you maybe provide a minimal repro project?

**Comment by pinguin999** [comment] 2024-04-30 09:10
@badlogic Hi thanks for your feedback. 
To reproduce the problem you have to scale the middlemiddle bone.
https://github.com/pinguin999/ALPACA/blob/main/src/dialog/speech_bubble.cpp#L16

Hope that helps to reproduce it.

**Comment by badlogic** [comment] 2024-05-02 14:01
Thank you! I was able to reproduce the issue and just pushed a fix to the 4.2 branch.

**Closed as completed** 2024-05-02 14:01 UTC

**Comment by pinguin999** [comment] 2024-05-02 14:31
I can confirm it's fixed!
