### ISSUE TITLE
[unity] skeletonDataAsset == null

### ISSUE THREAD

**Issue by kenxue007** [EsotericSoftware/spine-runtimes#2052] opened 2022-03-31 07:57 UTC
sometimes, when i launch app, skeletonDataAsset change into null.

below is stack trace.
error !!! : skeleton asset isn't exist!   guangqiashengli1
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
Spine.Unity.SkeletonGraphic:Initialize (bool) (at Assets/ThirdPart/Spine/Runtime/spine-unity/Components/SkeletonGraphic.cs:505)
Spine.Unity.SkeletonGraphic:Awake () (at Assets/ThirdPart/Spine/Runtime/spine-unity/Components/SkeletonGraphic.cs:217)

**Comment by HaraldCsaszar** [comment] 2022-03-31 16:47
Forum thread URL for later reference:
http://esotericsoftware.com/forum/skeletonDataAsset-null-17330

Sorry to hear you're having troubles!
We have resolved a similar issue in the past. Which version of the spine-unity runtime (name of the unitypackage, also listed in Assets/Spine/version.txt) are you using?

**Comment by HaraldCsaszar** [comment] 2022-06-02 13:25
Closing the issue since we did not yet receive the required reproduction project.
We are happy to reopen the issue once we can reproduce the problem.

**Closed as completed by HaraldCsaszar** 2022-06-02 13:25 UTC
Labels: bug

**Comment by nerdt** [comment] 2022-07-21 08:44
Same here, I pack all related spine's assets to a bundle A, and prefab which use these spine pack to bundle B.
When play in android or andorid simulator, First i load bundle A and B, then load prefab, then found the skeletonDataAsset be null sometimes, it happenes very few times. 
Here is some info:
Unity version 2020.3.17
Spine version  3.7.xx

**Comment by HaraldCsaszar** [comment] 2022-07-21 16:29
That sounds like you likely didn't ensure that your asset bundles have completed loading in the proper order. Try loading A before B before the prefab bundle, not A and B concurrently.

**Comment by nerdt** [comment] 2022-07-22 02:15
Thanks for reply. 
I did load A before B, and still be null. so we modify the SkeletonGraphic.cs Initialize() like this:
``` 
                  public void Initialize (bool overwrite) {
			if (this.IsValid && !overwrite) return;

			// force load from ab
			if (this.skeletonDataAsset == null) {
				var bundle = loadBundle();
				var skeDataAsset = bundle.LoadAsset<SkeletonDataAsset>(skeDataName);
				if (skeDataAsset != null) {
					this.skeletonDataAsset = skeDataAsset;
				}
			}

			// Make sure none of the stuff is null
			if (this.skeletonDataAsset == null) {
				return;
			}
```
then we found  the skeDataAsset(load from AB)  is still be null sometimes, its there any serialize problem when  SkeletonDataAsset load from AB, it's only happend very few times(same device same spine).
I will keep digging, Thanks for your reply again

**Comment by HaraldCsaszar** [comment] 2022-07-22 07:39
It may sound like a stupid question, but did you ensure that the asset bundle A has completed loading before starting to download asset bundle B, and that this has completed downloading before accessing the prefab?

**Comment by HaraldCsaszar** [comment] 2022-07-22 07:41
It may sound like a stupid question, but did you ensure that the asset bundle A has completed loading before starting to download asset bundle B, and that this has completed downloading before accessing the prefab? I'm asking since the code you posted does not show the relevant code sections.

**Comment by nerdt** [comment] 2022-07-22 07:56
sure all bundle loaded completed,  also before load SkeletonDataAsset from bundle, i check the assets exist by AssetBundle.Contains() and its return TRUE

**Comment by HaraldCsaszar** [comment] 2022-07-22 08:00
A side note: it is also a perfectly valid alternative way to start downloading all required packages at the same time instead of waiting for completion. Then you would manually re-assign any cross-bundle references via script after all downloads are complete. This would be better in terms of overall download time, but of course requires more re-assignment setup work.

**Comment by HaraldCsaszar** [comment] 2022-07-22 08:10
> sure all bundle loaded completed, also before load SkeletonDataAsset from bundle, i check the assets exist by AssetBundle.Contains() and its return TRUE

Maybe you misunderstood. I was asking whether the first bundle completed before you started downloading the second (and whether you ensure that it is complete before starting the second download). Not if all bundles completed before you access any assets.

**Comment by nerdt** [comment] 2022-07-22 08:14
I will do check again, Thanks for your reply
