### ISSUE TITLE
[spine-pixi]Some problems of spine-pixi

### ISSUE THREAD

**Issue by dragonbaba** [EsotericSoftware/spine-runtimes#2568] opened 2024-07-03 09:33 UTC
I have talked about something on the email, and now here I list it especially
I correct the files of Spine-Pixi during the runtime file
In Spine-Pixi Slotmesh.ts file, UpdateFromSpineData (), The current method has a large number of this.geometry.getBuffer calls. Each time you execute this statement, you will read the current binding attribute Attrubute from the webgl. Let vertexbuffer = Geometry.getBuffer ("Atexturecoord"). Data; Then determine whether the current BUFFER condition is met, and the conditions are not met to re -assign the new Float32array to Vertexbuffer;
Secondly, in Spine.Ts, the following operation of the following operation of the following operation if (Attachment InstanceOFIONACHMENT) {} Else IF (Attachment Instancetachment) {}, Instance f is used to obtain an example, I know you are going to get it The current attachment type, so why not add it in the constructor of the regionattachment, this distinction between this.type = "region"? , Then you can change this code to const type = Attachment.type; Switch (Type) case "region": case "mesh"; case "clip" is not faster in terms of logical or execution efficiency? 
Then there is the cache of Mesh, getMeshforslot, the method you provide is to use MAP as a mapping for cache, but the MAP's duration is very large.For how to modify, I can provide the following code, in Spine
Create this.meSheScache = [];
    this.meShesnamecache = object.create (null) Modify GetMeshforslot (Slot) {
      const attachment = slot.attachment;
      const key = Attachment.name;
      const namecache = this.Meshesnamecache;
      const cache = this.Meshescache;
      const index = Reflect.get (namecache, key) || -1;
      let Mesh = Cache[Index];
      if (mesh === void 0) {{
        mesh = this.slotmeshfactory ();
        this.addchild (Mesh);
        namecache [key] = this.meshcount ++;
        cache.push (Mesh);
        return Mesh;
      } Else {
        mesh.visible = true;
        return Mesh;
      }
    }
Quickly query the index stored in the current name storage through the object, quickly obtain the Mesh stored in the array through the index, remove and modify the Mesh, and only need to modify the MeshnameCache. When traversing the Mesh each time, you only need to perform the MESH array. He is much faster than MAP. The MAP object is essentially a double -array structure. Whether it is a key inquiry or a value inquiry, it requires two -way traversal, which is very slow, and the access of object attributes is very fast, especially the modern JS engine. Essence Brother, your code habit is not very good, don't ignore the tips and warnings brought by the TS editor. Enjoying the characteristics of modern high -end APIs is to achieve the function quickly. If the elder brother has any places or places where there is any conflict, we can communicate friendly. At the same time The performance detection tool that comes is still very useful

**Comment by davidetan** [comment] 2024-07-03 09:40
Duplicate of #2569.

**Closed as not planned by davidetan** 2024-07-03 09:40 UTC
