### ISSUE TITLE
[unity] TK2D SpriteCollectionAttachmentLoader compile errors on 4.1

### ISSUE THREAD

**Issue by soqman** [EsotericSoftware/spine-runtimes#2113] opened 2022-07-14 12:00 UTC
use TK2D 
SpriteCollectionAttachmentLoader not compile:
 - has not interface method updates (no big problem)
 - how to set material to TextureRegion or need to use AtlasRegion instead?

**Comment by HaraldCsaszar** [comment] 2022-07-14 12:34
Thanks for reporting and sorry for the troubles! It is surprising to see active TK2D users still.
Please note that spine-unity 4.1 will be the last version that supports TK2D, after this compile error has been fixed.

**Comment by HaraldCsaszar** [comment] 2022-07-14 17:56
We have committed a fix on the 4.1 branch. A new spine-unity 4.1 unitypackage is available for download here as usual:
http://esotericsoftware.com/spine-unity-download
Please let us know if this resolves your issues, or if you are still facing problems. If problems persist, could you please send us a minimal Unity reproduction project that demonstrates the issue, then we can more quickly provide any bugfix. You can send it as a zip package to contact@esotericsoftware.com (briefly mentioning the URL of this issue ticket so that we know the context), or post it here.

(Unfortunately my local TK2D test project seems to cause troubles for unknown reasons, not resolving `tk2dSpriteCollectionData`.)

**Comment by soqman** [comment] 2022-07-15 06:51
Thank you so much. I glad to know that there is support. 

1. Now, SkeletonAsset animations can load now. but a texture puts wrong way. It looks like uvs, size or rotation is broken. 
2. You can only attach a tk2dSpriteCollectionData with debug mode, because inspector resetting field normal way
3. I need to use multiple tk2dSpriteCollectionData.

**Comment by soqman** [comment] 2022-07-15 06:54
`(Unfortunately my local TK2D test project seems to cause troubles for unknown reasons, not resolving tk2dSpriteCollectionData.)`
you need to add tk2d library definition to spine runtime asmdef

**Comment by HaraldCsaszar** [comment] 2022-07-15 07:59
> you need to add tk2d library definition to spine runtime asmdef
Oh, of course, thanks for pointing that out, I forgot that re-importing the library has overwritten the previously setup asmdef files.
> Now, SkeletonAsset animations can load now. but a texture puts wrong way. It looks like uvs, size or rotation is broken.
> You can only attach a tk2dSpriteCollectionData with debug mode, because inspector resetting field normal way
> I need to use multiple tk2dSpriteCollectionData.
Can you please send us your Unity project as described above, then we can resolve these issues much faster.

**Comment by soqman** [comment] 2022-07-15 08:25
Unfortunately, this is an NDA. I can try assemble an empty project with the same problem, but I don't think the issue with textures is just our project's.

**Comment by HaraldCsaszar** [comment] 2022-07-15 09:10
Yes, please assemble an empty project. We never intended to get your whole project, it shall be a minimal Unity project that demonstrates these problems. Please understand that we don't have the resources to get acquinted to using TK2D again, since you might be the only remaining developer still using TK2D with Spine.

**Comment by soqman** [comment] 2022-07-16 14:53
Hello! I prepared a test project from scratch. All points are reproducable.
Also, send archive by email

[google disk url](https://drive.google.com/file/d/1w83cm8ksD20cSpfVHUucWGkVi0ouBVYF/view?usp=sharing)

**Comment by HaraldCsaszar** [comment] 2022-07-18 09:39
Thanks very much for posting your reproduction project. I will get back to you as soon as we have a bugfix to offer.

**Comment by HaraldCsaszar** [comment] 2022-07-18 11:32
The issues regarding incorrect UV coords and assignment of a sprite collection asset in the Inspector have just been resolved on the 4.1 branch. A new spine-unity unitypackage is available for download:
http://esotericsoftware.com/spine-unity-download

regarding "3) I need to use multiple tk2dSpriteCollectionData."
By that, do you mean that you would need an array instead of a single sprite collection that can be assigned in the inspector (and will be used to get regions from)? I'm mainly asking because this features was not available in the previous versions of the spine-unity TK2D implementation.

**Comment by soqman** [comment] 2022-07-18 13:15
Thanks a lot for the fix. I will write later after the test. About 3 - yes, you perfectly understood. Perhaps this functionality was added by our programmers. I can do it myself.

**Comment by HaraldCsaszar** [comment] 2022-07-18 14:19
Thanks for getting back to us. Looking forward to your test results.
> About 3 - yes, you perfectly understood. Perhaps this functionality was added by our programmers. I can do it myself.

Yes, unfortunately that hasn't been part of the official runtime. It would be great if you could add it yourself as mentioned.

**Comment by soqman** [comment] 2022-07-18 20:29
it works fine, except one point:

SpriteCollectionAttachmentLoader : 115 -116
```
region.width = regionRotated ? (int) regionHeight : (int)regionWidth;
region.height = regionRotated ? (int) regionWidth : (int)regionHeight;
```

if region is rotated in texture atlas it gets the wrong dimensions. so, i just swap it.
you can test it from project link below. maybe you can fix it in the best possible way.

[google-disk-url](https://drive.google.com/file/d/11NF0N5dlRAQFqhTa5V3w1v_E9x7VbNUW/view?usp=sharing)

p.s. no problems with multiple sprite assets. so, it works fine.

**Comment by HaraldCsaszar** [comment] 2022-07-19 15:03
Thanks for testing and for sharing your findings. I have downloaded your new reproduction Unity project above, unfortunatey I receive the following `Sprite not found in atlas: 1` error when selecting the SkeletonData asset:
```
Sprite not found in atlas: 1
UnityEngine.Debug:Log (object,UnityEngine.Object)
Spine.Unity.TK2D.SpriteCollectionAttachmentLoader:ProcessSpriteDefinition (string) (at Assets/Spine/Runtime/spine-unity/Modules/TK2D/SpriteCollectionAttachmentLoader.cs:61)
Spine.Unity.TK2D.SpriteCollectionAttachmentLoader:NewRegionAttachment (Spine.Skin,string,string,Spine.Sequence) (at Assets/Spine/Runtime/spine-unity/Modules/TK2D/SpriteCollectionAttachmentLoader.cs:136)
Spine.SkeletonBinary:ReadAttachment (Spine.SkeletonBinary/SkeletonInput,Spine.SkeletonData,Spine.Skin,int,string,bool) (at Assets/Spine/Runtime/spine-csharp/SkeletonBinary.cs:393)
Spine.SkeletonBinary:ReadSkin (Spine.SkeletonBinary/SkeletonInput,Spine.SkeletonData,bool,bool) (at Assets/Spine/Runtime/spine-csharp/SkeletonBinary.cs:365)
Spine.SkeletonBinary:ReadSkeletonData (System.IO.Stream) (at Assets/Spine/Runtime/spine-csharp/SkeletonBinary.cs:280)
Spine.Unity.SkeletonDataAsset:ReadSkeletonData (byte[],Spine.AttachmentLoader,single) (at Assets/Spine/Runtime/spine-unity/Asset Types/SkeletonDataAsset.cs:265)
Spine.Unity.SkeletonDataAsset:GetSkeletonData (bool) (at Assets/Spine/Runtime/spine-unity/Asset Types/SkeletonDataAsset.cs:171)
Spine.Unity.Editor.SkeletonDataAssetInspector:InitializeEditor () (at Assets/Spine/Editor/spine-unity/Editor/Asset Types/SkeletonDataAssetInspector.cs:147)
Spine.Unity.Editor.SkeletonDataAssetInspector:OnEnable () (at Assets/Spine/Editor/spine-unity/Editor/Asset Types/SkeletonDataAssetInspector.cs:84)
```

Are you sure that you've attached the right test project?

**Comment by soqman** [comment] 2022-07-19 16:33
[here](https://drive.google.com/file/d/1eeBUCCX1cAgM_E-LLDCw0R4-X0cMsBAm/view?usp=sharing)
now it works fine.

**Comment by HaraldCsaszar** [comment] 2022-07-20 09:24
Thanks for the second repro package, I could now reproduce the issue. An official fix has been committed which is very similar to your provided implementation. A new 4.1 unitypackage has been released.

I will now close this issue, in case you find anything else remaining that requires fixing, just let us know an we will reopen this ticket. Thanks again for reporting!

**Closed as completed by HaraldCsaszar** 2022-07-20 09:24 UTC
Labels: bug
