### ISSUE TITLE
[ue4] Random crashes in delegate broadcast

### ISSUE THREAD

**Issue by erdelf** [EsotericSoftware/spine-runtimes#1264] opened 2019-01-23 14:53 UTC
We've been getting a lot of crashes recently in our project that uses spine extensively.
After a lot of testing, I did limit it to the AnimationComplete Delegate. 
If I never bind anything to it (and don't have the respective event) it doesn't crash.
Even just having the event without any connections causes a crash.

Tried the fix idea in #1190 but that just causes the character to go invisible (probably clearing the skeleton is the cause of that).

The debugger is sadly not giving out any clear cause.. sometimes it seems the delegate has 5 million bindings, sometimes the input evt is completely full of invalid values.

(line number in spineskeletonanimationcomponent.cpp is off because of debugging code)

```
Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION 0x00000000

0x0000000000000000 UnknownFunction []
0x00007fffcc711201 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007fffcc72f499 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007fffcc761e77 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007fffcc731b96 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007fffcc71205d UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007fffcc731b96 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007fffcc506467 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007fffcc731133 UE4Editor-CoreUObject.dll!UnknownFunction []
0x00007fffc3988033 UE4Editor-Engine.dll!UnknownFunction []
0x00007fff9e3c6071 UE4Editor-SpinePlugin.dll!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [e:\games\unreal engine\ue_4.20\engine\source\runtime\core\public\uobject\scriptdelegates.h:462]
0x00007fff9e3df888 UE4Editor-SpinePlugin.dll!callback() [c:\users\erdelfion\perforce\erdelf_mdh\thunderstorm\plugins\spineplugin\source\spineplugin\private\spineskeletonanimationcomponent.cpp:76]
0x00007fff9e407db6 UE4Editor-SpinePlugin.dll!spine::EventQueue::drain() [c:\users\erdelfion\perforce\erdelf_mdh\thunderstorm\plugins\spineplugin\source\spineplugin\public\src\spine\animationstate.cpp:240]
0x00007fff9e3fc2a5 UE4Editor-SpinePlugin.dll!spine::AnimationState::apply() [c:\users\erdelfion\perforce\erdelf_mdh\thunderstorm\plugins\spineplugin\source\spineplugin\public\src\spine\animationstate.cpp:442]
0x00007fff9e3dbbc9 UE4Editor-SpinePlugin.dll!USpineSkeletonAnimationComponent::InternalTick() [c:\users\erdelfion\perforce\erdelf_mdh\thunderstorm\plugins\spineplugin\source\spineplugin\private\spineskeletonanimationcomponent.cpp:114]
0x00007fffc3cbec21 UE4Editor-Engine.dll!UnknownFunction []
0x00007fffc3cf99c4 UE4Editor-Engine.dll!UnknownFunction []
0x00007fffc4b616bd UE4Editor-Engine.dll!UnknownFunction []
0x00007fffc8cf1f92 UE4Editor-Core.dll!UnknownFunction []
0x00007fffc8cf2456 UE4Editor-Core.dll!UnknownFunction []
0x00007fffc8d06d25 UE4Editor-Core.dll!UnknownFunction []
0x00007fffc4bb5b04 UE4Editor-Engine.dll!UnknownFunction []
0x00007fffc4bc4d92 UE4Editor-Engine.dll!UnknownFunction []
0x00007fffc42c87e4 UE4Editor-Engine.dll!UnknownFunction []
0x00007fffc42d4003 UE4Editor-Engine.dll!UnknownFunction []
0x00007fffc7967335 UE4Editor-UnrealEd.dll!UnknownFunction []
0x00007fffc825f666 UE4Editor-UnrealEd.dll!UnknownFunction []
0x00007ff7f5b45cbd UE4Editor.exe!UnknownFunction []
0x00007ff7f5b55b3c UE4Editor.exe!UnknownFunction []
0x00007ff7f5b55bba UE4Editor.exe!UnknownFunction []
0x00007ff7f5b63dac UE4Editor.exe!UnknownFunction []
0x00007ff7f5b65aaa UE4Editor.exe!UnknownFunction []
0x00007ff82d4b81f4 KERNEL32.DLL!UnknownFunction []
0x00007ff82fb2a251 ntdll.dll!UnknownFunction []
```

**Comment by badlogic** [comment] 2019-01-23 15:47
Thanks for reporting and sorry for the trouble. Is there any chance you could provide me with a reproduction sample? When the other issue was filed, I tried more approaches than I can count to get this to reproduce on my end. I'm afraid without a way for me to reproduce it locally, there's not much I can do :/

**Comment by erdelf** [comment] 2019-01-23 15:55
Thanks for the quick answer.
That makes perfect sense, yeah. I'll see if I can make a reproducible sample outside of our current project.

**Comment by erdelf** [comment] 2019-01-23 19:49
Just to give an update. Making a reproducible sample proves harder than thought... even when using a map that causes a reproducible crash in my main project.

Sadly I am not allowed to give out the project like that...

**Comment by erdelf** [comment] 2019-01-27 18:08
just for clarification, did one of your tests include level streaming?
While the crashes aren't perfectly reproducible, they always happen right after a level unloaded.

**Comment by badlogic** [comment] 2019-01-28 10:19
@erdelf no, my tests did not include level streaming, but this gives us a bit of a clue. Since you can somewhat reliably reproduce this, could you try to unregister the delegates right before the level transition happens? If this fixes your crashes, then we 1) have a temporary workaround for you and 2) have an idea where to look next.

**Comment by erdelf** [comment] 2019-01-28 14:41
So we have our clue. Unbinding all events from AnimationComplete from the Dispatcher OnLevelHidden solved the crash in my so far reliable test case.

![BlueprintScreenshot](https://imgur.com/62GRaPc.png)

**Comment by badlogic** [comment] 2019-01-28 14:54
That's somewhat good news. Now I need to figure out why the delegates fire
after the corresponding UObject has become invalid.

Thanks a lot for helping out with this!

**Comment by badlogic** [comment] 2019-04-26 12:53
I believe this is fixed now with the latest changes in the 3.8-beta branch. Please report back if you still run into this issue.

**Closed as completed by badlogic** 2019-04-26 12:53 UTC
Labels: bug

**Comment by someblue** [comment] 2019-08-15 02:48
Hi @badlogic , I encounter this problem too, at v3.8 (commit id b151e2e, Aug 9)

Here is my logs:

```
[2019.08.14-12.27.19:004][536]LogWindows: Error: === Critical error: ===
[2019.08.14-12.27.19:004][536]LogWindows: Error: 
[2019.08.14-12.27.19:004][536]LogWindows: Error: Fatal error!
[2019.08.14-12.27.19:004][536]LogWindows: Error: 
[2019.08.14-12.27.19:004][536]LogWindows: Error: Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffff
[2019.08.14-12.27.19:004][536]LogWindows: Error: 
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff8205d6890 UE4Editor-SpinePlugin.dll!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [d:\application\epic games\ue_4.21\engine\source\runtime\core\public\uobject\scriptdelegates.h:485]
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff82061684f UE4Editor-SpinePlugin.dll!callback() [c:\workspace\meowth\meowthdemo\plugins\spineplugin\source\spineplugin\private\spineskeletonanimationcomponent.cpp:52]
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff82061f864 UE4Editor-SpinePlugin.dll!spine::EventQueue::drain() [c:\workspace\meowth\meowthdemo\plugins\spineplugin\source\spineplugin\public\spine-cpp\src\spine\animationstate.cpp:259]
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff8205fd2d0 UE4Editor-SpinePlugin.dll!USpineSkeletonAnimationComponent::InternalTick() [c:\workspace\meowth\meowthdemo\plugins\spineplugin\source\spineplugin\private\spineskeletonanimationcomponent.cpp:112]
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff832079cd4 UE4Editor-Engine.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff83209e704 UE4Editor-Engine.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff832f04a2d UE4Editor-Engine.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff842b61798 UE4Editor-Core.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff842b619e0 UE4Editor-Core.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff832f5b949 UE4Editor-Engine.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff832f6b9a2 UE4Editor-Engine.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff83263b6e4 UE4Editor-Engine.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff8326479d9 UE4Editor-Engine.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff835242085 UE4Editor-UnrealEd.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff835b62346 UE4Editor-UnrealEd.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff674d46225 UE4Editor.exe!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff674d5596c UE4Editor.exe!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff674d559ea UE4Editor.exe!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff674d648da UE4Editor.exe!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff674d6659a UE4Editor.exe!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff88b957974 KERNEL32.DLL!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: [Callstack] 0x00007ff88d78a271 ntdll.dll!UnknownFunction []
[2019.08.14-12.27.19:004][536]LogWindows: Error: 
[2019.08.14-12.27.19:012][536]LogExit: Executing StaticShutdownAfterError
[2019.08.14-12.27.19:143][536]LogWindows: FPlatformMisc::RequestExit(1)
[2019.08.14-12.27.19:149][536]Log file closed, 08/14/19 20:27:19
```

I bind AnimationComplete event to get notification when animation finish. And then unbind this event because I need to SetAnimation to play next animation and the previous TrackEntry is unused.

This crash happen randomly. But when I play long enough, this crash will happen eventually (sometimes 1min, sometimes 10min)

![image](https://user-images.githubusercontent.com/5562124/63069536-d21acb80-bf49-11e9-82c9-9e5551ff5348.png)

**Comment by FrankFoetus** [comment] 2019-12-30 16:21
Hi,
I have a very similar problem. My program crashes when I am trying to build a mesh section of a procedural mesh of an actor in my level.

Usually it worked just fine, but now I programmed the runtime import of a model, the user previously chose, in c++ asynchronously with delegates in an FAutoDeleteAsyncTask.

I unbind all delegates and delete the actor (ImportManager) I created for the asynchronous import, after it is finished (call sent to the delegate), but still the delegates that I declared in the h file of that ImportManager interfere with the creation of the mesh section.

I have no idea why the delegates even exist anymore. Any help would be apreciated.


Error Track: 

```
Assertion failed: IsInGameThread() [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/PhysicsCore/Private/PhysXPublicCore.cpp] [Line: 93]

UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_PhysicsCore
UE4Editor_Engine
UE4Editor_ProceduralMeshComponent
UE4Editor_ProceduralMeshComponent
UE4Editor_ProceduralMeshComponent
UE4Editor_ProceduralMeshComponent
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_CoreUObject
UE4Editor_Showroom!TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [c:\program files\epic games\ue_4.23\engine\source\runtime\core\public\uobject\scriptdelegates.h:488]
UE4Editor_Showroom!FExtractMeshSectionsSignature::Broadcast() [c:\users\robin\documents\infinitygate\showroom\source\showroom\public\importmanager.h:33]
UE4Editor_Showroom!SceneImportAsyncTask::DoWork() [c:\users\robin\documents\infinitygate\showroom\source\showroom\public\importmanager.h:302]
UE4Editor_Showroom!FAutoDeleteAsyncTask<SceneImportAsyncTask>::DoWork() [c:\program files\epic games\ue_4.23\engine\source\runtime\core\public\async\asyncwork.h:100]
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
kernel32
ntdll
```

**Comment by Misarte** [comment] 2022-05-02 12:11
I had a similar issue and would like to post my findings in case someone encounters it:

- I have a cpp Actor Component attached on a CharacterPawn object.
- The ActorComponent defines and brodcasts a multicast delegate event called OnComponentMove(float x, float y)
- Within the CharacterPawn blueprint: OnBeginPlay binds  to OnCharacterMove and performs MoveToLocation with AIController whenever the event is firing.
- When my CharacterPawn was already at the destination the event was broadcasting, UE crashed with the above error (but on different line ):
``` TMulticastScriptDelegate<FWeakObjectPtr>::ProcessMulticastDelegate<UObject>() [..\uobject\ScriptDelegates.h:488] ```

The error was resolved by introducing a Brach before the MoveToLocation,  that checks if the X, Y (Z not important in my setup) are almost same as the Characters GetActorLocation X and Y and if the are it bypasses the function MoveToLocation. 

Note: One thing that I still do not understand is why the breakpoint added within the CharacterPawn blueprint on the MoveToLocation is not being hit, however the function is executed accordingly.
