### ISSUE TITLE
[ue4]Render in wrong transparency

### ISSUE THREAD

**Issue by jashking** [EsotericSoftware/spine-runtimes#1553] opened 2019-11-26 09:02 UTC
In my [demo project](https://github.com/EsotericSoftware/spine-runtimes/files/3890860/SpineFlicker.zip), the four wheels are rendered in the wrong transparency, it's not the same result as in the spine editor

![spine](https://user-images.githubusercontent.com/2841098/69614649-6b3f9f00-106e-11ea-99c2-148635228a0b.gif)

**Comment by jashking** [comment] 2019-11-26 12:37
Hi, here is the [Spine Project](https://github.com/EsotericSoftware/spine-runtimes/files/3891844/WheelProject.zip), Please check out

**Comment by jashking** [comment] 2019-11-27 09:33
Hi, can you reproduce this issue?

**Comment by badlogic** [comment] 2019-11-27 09:34
Sorry, I haven't had time to look into it. I'll do so tomorrow.

**Comment by jashking** [comment] 2019-11-27 09:40
Ok, our game is about to ship, so it would be nice if you look into this issue as soon as possible, thanks

**Comment by badlogic** [comment] 2019-11-28 13:36
I've tried to repro this using your demo project. I couldn't see flicker on Windows. What platform do you see flicker on?

**Comment by badlogic** [comment] 2019-11-28 13:51
I had another look into your Spine project. The UE4 renderer actually does the correct thing. What's different to the editor is the background color. In this editor, you test using the gray checker background. In UE4, you have a bright blue background. That results in different blending results.

You can get the flicker in Spine as well by setting the background to "solid" and a bright color:

![https://marioslab.io/uploads/screenshots/JDelN1M9oS.png](https://marioslab.io/uploads/screenshots/JDelN1M9oS.png)

(You won't be able to see the flicker in that single screenshot, it's just to show what my test setup was).

I'm not quite sure what your animators where trying to achieve with the setup of cycling colors, but the rendering is correct. I have asked Erika to chime in here. Since this is not a bug in the UE4 runtime, I'm closing the issue.

**Closed as completed by badlogic** 2019-11-28 13:51 UTC
Labels: bug

**Comment by erikari** [comment] 2019-11-28 13:58
I confirm what @badlogic said. The flicker happens at inbetween positions because images are cross-transitioning from solid to transparent, just add a solid image as base that doesn't ever fade out and the flicker will be gone :D
