### ISSUE TITLE
[ts] After upgrade to pixi v4.2.47 we got an issue there is a shadow in the animation

### ISSUE THREAD

**Issue by hotyes** [EsotericSoftware/spine-runtimes#2561] opened 2024-06-26 03:24 UTC
Anyone got similar issue before? thanks

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/34628616/cdb47cb7-3e1a-45ae-b280-0ffda9737a20)

**Comment by davidetan** [comment] 2024-06-26 07:00
Hi @hotyes, I'm sorry to hear that.
We actually made some fixes about colors, but in all our examples I didn't see this kind of problem.

Can you share the project with us or a minimal reproduction project?
If you cannot share the probject here you can also send it to [contact@esotericsoftware.com](mailto:contact@esotericsoftware.com).

**Comment by hotyes** [comment] 2024-06-26 12:01
hi @davidetan, email sent, please help to check, thanks

**Comment by davidetan** [comment] 2024-06-26 12:47
Email received, thx!
I confirm I can easily reproduce the bug now. I'll work on fixing it 👍

**Comment by davidetan** [comment] 2024-06-26 13:56
The regression has been fixed in version `4.2.48`.
Thanks again for reporting this and for your support in providing the example project!

**Closed as completed by davidetan** 2024-06-26 13:56 UTC

**Comment by hotyes** [comment] 2024-06-27 03:48
Hi @davidetan, thanks for the fix, confirmed it was fixed in 4.2.48, but I think I ran into another bug, one of my animations would flicker, not sure where the problem is

**Comment by davidetan** [comment] 2024-06-27 06:38
> Hi @davidetan, thanks for the fix, confirmed it was fixed in 4.2.48, but I think I ran into another bug, one of my animations would flicker, not sure where the problem is

Sorry to hear that. I went through all our examples and I didn't see any flickering problem.
Feel free to open a new issue or just send us another project containing this new issue.
I'll be more than happy to help you :)

**Comment by hotyes** [comment] 2024-07-01 10:01
hi @davidetan is seems it can be solved by calling `animation.update(0)` immediately after creating spine animation.

for example
```
const animation = Spine.from(skeleton, atlas)
animation.state.setAnimation(trackIndex, animName, false)
animation.update(0) // <- without this line I got a flickering problem
```

is this intentional?

**Comment by davidetan** [comment] 2024-07-01 10:09
> hi @davidetan is seems it can be solved by calling `animation.update(0)` immediately after creating spine animation.
> 
> for example
> 
> ```
> const animation = Spine.from(skeletion, atlas)
> animation.state.setAnimation(trackIndex, animName, false)
> animation.update(0) // <- without this line I got a flickering problem
> ```
> 
> is this intentional?

No, that's not intentional and it's likely to be a bug :(
I'm not able to reproduce the issue with our examples.
Any chance you can send us a minimal reproduction project for the issue?
