### ISSUE TITLE
[corona] Slot colors ar darkened by low alpha values

### ISSUE THREAD

**Issue by torbenratzlaff** [EsotericSoftware/spine-runtimes#988] opened 2017-09-12 13:02 UTC
The current implementation of colering graphics darkens those with a low alpha value.
This appears, because a slots color values are multiplied with its alpha value, which leads to darker colors.

This can be solved by changing the block of code in the updateWorldTransform function in the spine-corona lua file.

Old
`color:set(skeletonColor.r * slotColor.r * attachmentColor.r * multiplier,
		skeletonColor.g * slotColor.g * attachmentColor.g * multiplier,
		skeletonColor.b * slotColor.b * attachmentColor.b * multiplier,
		alpha)`

New (multiplier is obsolete now)
`color:set(skeletonColor.r * slotColor.r * attachmentColor.r,
		skeletonColor.g * slotColor.g * attachmentColor.g,
		skeletonColor.b * slotColor.b * attachmentColor.b,
		alpha)`

**Comment by badlogic** [comment] 2017-09-13 07:13
Could you provide me with an example for this issue? The multiplier is used to discern between premultiplied alpha and non-premultiplied alpha.

**Comment by badlogic** [comment] 2017-09-25 13:26
@torbenratzlaff just wanted to bump this. do you have a reproduction case for me to verify the issue?

**Comment by badlogic** [comment] 2017-09-27 10:26
Can't reproduce. Closing this out.

**Closed as completed by badlogic** 2017-09-27 10:26 UTC
