### ISSUE TITLE
PolygonSpriteBatch doesn't have transparent [Libgdx Spine runtime]

### ISSUE THREAD

**Issue by MrGru** [EsotericSoftware/spine-runtimes#556] opened 2016-04-19 10:06 UTC
I use Libgdx spine runtime with polygonSpiteBatch, but it doesn't have transparent?

**Comment by NathanSweet** [comment] 2016-05-10 10:46
It doesn't have transparency? Please ensure the premultiplied alpha texture atlas setting matches the premultiplied alpha setting on the SkeletonMeshRenderer.

**Comment by badlogic** [comment] 2016-07-18 12:51
Closing this out, works as intended.

**Closed by badlogic** 2016-07-18 12:51 UTC
Labels: runtimes
