### ISSUE TITLE
[unity] Exception when separated empty mesh at SkeletonGraphic

### ISSUE THREAD

**Issue by supermoos** [EsotericSoftware/spine-runtimes#2364] opened 2023-09-14 09:32 UTC
I get this error when setting up multiple renderers to try and render an arm on a seperate order from the body.

`NullReferenceException: Object reference not set to an instance of an object
Spine.Unity.SkeletonGraphic.UpdateMaterialsMultipleCanvasRenderers (Spine.Unity.SkeletonRendererInstruction currentInstructions) (at Assets/Spine/Runtime/spine-unity/Components/SkeletonGraphic.cs:845)
Spine.Unity.SkeletonGraphic.UpdateMeshToInstructions () (at Assets/Spine/Runtime/spine-unity/Components/SkeletonGraphic.cs:753)
Spine.Unity.SkeletonGraphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at Assets/Spine/Runtime/spine-unity/Components/SkeletonGraphic.cs:317)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs:215)
UnityEngine.Canvas:SendWillRenderCanvases() (at /Users/bokken/build/output/unity/unity/Modules/UI/ScriptBindings/UICanvas.bindings.cs:96)
`
Here's the settings:
<img width="434" alt="Screenshot 2023-09-14 at 11 30 33" src="https://github.com/EsotericSoftware/spine-runtimes/assets/2298345/c905780e-342f-433a-b814-b1e792de97d9">
And the gameobjects it auto-creates:
<img width="128" alt="Screenshot 2023-09-14 at 11 31 00" src="https://github.com/EsotericSoftware/spine-runtimes/assets/2298345/16ab01f7-8415-4e2c-8dd8-7a1d199874dc">
And a snapshot of the Renderer0 object:
<img width="444" alt="Screenshot 2023-09-14 at 11 31 07" src="https://github.com/EsotericSoftware/spine-runtimes/assets/2298345/3194c4fb-6c18-4720-ae60-796b91037012">

When I play the scene now nothing renders.

**Comment by HaraldCsaszar** [comment] 2023-09-14 09:45
@supermoos Sorry to hear you're having troubles. Unfortunately the information provided is not sufficient for us to reproduce the issue.

Which exact version (including the date) of the spine-unity runtime are you using? You can find it as name of the unitypackage, or in `Assets/Spine/version.txt`. Alternatively you can share the version displayed in the Unity Package Manager. If you're not using the latest package version, please update and check if the issue is resolved.

Otherwise, can you please send us a minimal Unity project which still shows this issue? You can send it to contact@esotericsoftware.com, briefly mentioning this ticket URL so that we know the context.
Closing this issue intermediately, we're happy to re-open it once we can reproduce the issue.

**Closed as completed by HaraldCsaszar** 2023-09-14 09:45 UTC

**Comment by supermoos** [comment] 2023-09-14 12:53
Done :)

**Comment by HaraldCsaszar** [comment] 2023-09-14 13:39
@supermoos Thanks for sending the reproduction project, we could reproduce this exception now. Please note that what you're doing makes no sense, you're separating the skeleton at slot `L_ARM` which is the first slot in the draw order (after a mask attachment), so you're splitting the mesh into two parts containing [nothing][everything]. Likely you incorrectly assumed that separation works on the bone hierarchy instead of draw order.

Nevertheless, it should not fail with a null-reference-exception. We have fixed this exception, a new 4.1 spine-unity package is available for download:
https://esotericsoftware.com/spine-unity-download
