### ISSUE TITLE
[ue4] Unable to Build project with nativization (SpineSkeletonRendererComponent.h No such file or directory)

### ISSUE THREAD

**Issue by raxi2012** [EsotericSoftware/spine-runtimes#2042] opened 2022-03-12 18:05 UTC
Hello, with Spine-Runtime 4.0.31 and latest from 4.0 branch I unable to compile any UE4 projects with nativization enabled

UATHelper: Packaging (Windows (64-bit)):     C:/Users/Raxi/Documents/Unreal Projects/Related_SourceCode/Intermediate/Plugins/NativizedAssets/Windows/Game/Source/NativizedAssets/Private/Jess__pf2626391809.cpp(8): fatal error C1083: Cannot open include file: '../Plugins/SpinePlugin/Source/SpinePlugin/Public/SpineSkeletonRendererComponent.h': No such file or directory

Log:
UATHelper: Packaging (Windows (64-bit)):   Building 11 actions with 8 processes...
UATHelper: Packaging (Windows (64-bit)):     [1/11] turbojpeg.dll
UATHelper: Packaging (Windows (64-bit)):     [2/11] Default.rc2
UATHelper: Packaging (Windows (64-bit)):     [3/11] SharedPCH.Core.cpp
UATHelper: Packaging (Windows (64-bit)):     [4/11] Reborn.cpp
UATHelper: Packaging (Windows (64-bit)):     [5/11] SharedPCH.Engine.cpp
UATHelper: Packaging (Windows (64-bit)):     [6/11] Module.NativizedAssets.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [7/11] Module.SpinePlugin.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [8/11] Module.NativizedAssets.cpp
UATHelper: Packaging (Windows (64-bit)):     C:/Users/Raxi/Documents/Unreal Projects/Related_SourceCode/Intermediate/Plugins/NativizedAssets/Windows/Game/Source/NativizedAssets/Private/Jess__pf2626391809.cpp(8): fatal error C1083: Cannot open include file: '../Plugins/SpinePlugin/Source/SpinePlugin/Public/SpineSkeletonRendererComponent.h': No such file or di
rectory
UATHelper: Packaging (Windows (64-bit)):     [9/11] Module.SpinePlugin.cpp
UATHelper: Packaging (Windows (64-bit)): Took 45.1469989s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\Raxi\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.26\UBT-Reborn-Win64-Shipping.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error
![log](https://user-images.githubusercontent.com/17443915/158029426-a7ddac4e-1f82-4050-ad0e-b029a1710ff4.jpg)

**Comment by badlogic** [comment] 2022-03-12 20:47
What does your project's `Build.cs` file look like? What UE4 version are you using?

**Comment by lukeeingram** [comment] 2022-03-23 17:25
Hello, I checked into your issue, but I was unable to reproduce it.
I built and compiled our example projects both with and without nativization enabled.

If you could, please check your include paths in your `Build.cs`, and compare your `Build.cs` to the one that is included in our sample projects.
If you are still unable to build or compile with nativization enabled, could you please provide us with a minimal project that could help us reproduce your issue?

**Closed as completed by lukeeingram** 2022-03-23 17:25 UTC
Labels: bug

**Comment by lukeeingram** [comment] 2022-03-23 17:35
Also, as a note, please double-check that you properly copied the spine-cpp folder from step 7 of our spine-ue4 setup instructions.
Please see this page for the setup instructions: http://en.esotericsoftware.com/spine-ue4#Installation
