### ISSUE TITLE
Check proper tint black blending for non-PMA images

### ISSUE THREAD

**Issue by NathanSweet** [EsotericSoftware/spine-runtimes#992] opened 2017-09-14 12:15 UTC
We should verify non-PMA blending is incorrect when using tint black. Consider a single formula to combine PMA and non-PMA cases, where `u_pma` is a uniform which is 1 for PMA and 0 for non-PMA:
```
gl_FragColor.rgb = (u_pma + (1.0 - u_pma) * texColor.a - texColor.rgb) * v_dark.rgb +
                   texColor.rgb * v_light.rgb; 
```

**Comment by ivanpopelyshev** [comment] 2017-09-14 12:24
Ok, so, which branch should i make PR against?

Whole idea of two-tint looks like that: We have to map [0..1] color into [dark..light], independent from alpha. Alpha works like always. There's no "dark alpha" nor"light alpha", just one alpha.

# Premultiplied

BlendMode : (1, 1-src_alpha)
v_light, v_dark are premultiplied by alpha, u_pma is 0.0 and is packed as a "v_dark.a" but it has no logic relation to the dark side. Don't look at that its used in same multiplication as v_dark, its just a coincindence, there's no such thing as "dark alpha"

# NON-PMA

BlendMode : (src_alpha, 1-src_alpha)
u_pma is 1.0, v_light and v_dark are non-premultiplied.

**Comment by ivanpopelyshev** [comment] 2017-09-14 12:31
Also, you guys are much better than me in testing, I'm just a math guy. If we succeed, I'll add it to pixi.js and may be I add it to CanvasRenderer too! Also we'll try bunnymark two shaders, may be we can use two-tint shader by default.

Btw, tint can be packed into 4 bytes, and dark-light into 8. Right now runtime is packing it into 4 floats, which is not optimal.

**Comment by ivanpopelyshev** [comment] 2017-09-14 15:06
Ok, now PMA is 1.0 for premultiplied. Please check it in PR.

**Comment by badlogic** [comment] 2017-09-25 10:07
I've tested the PR by @ivanpopelyshev and it works as intended for tint black in both PMA and none PMA mode. However, this issue is about verifying that non-PMA tint black is broken. @NathanSweet any pointers on how to do that?

**Comment by ivanpopelyshev** [comment] 2017-09-25 11:07
something like TEXTURE=0x707070, TEXTURE_ALPHA=0.5 with DARK=0x707070 will show the difference in both pma and non-pma modes. Current formula is just wrong for both cases.

**Comment by badlogic** [comment] 2017-09-25 12:29
I wrote a quick test https://github.com/EsotericSoftware/spine-runtimes/blob/3.6/spine-ts/webgl/example/test-pma-tintblack.html

It loads two textures, one non-pma, one pma. It then renders either one of the textures using pma or non-pma blending as well as the light and dark colors you can specify in hex in the first two fields.

Seems non-pma tint black is indeed broken:

Outputs (see form state for config):

**non-PMA, dark: 0x000000**
![https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-09-25%20at%202.25.56%20PM-YU3HKBLXDo.png](https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-09-25%20at%202.25.56%20PM-YU3HKBLXDo.png)

**PMA, dark: 0x000000**
![https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-09-25%20at%202.27.32%20PM-ZWaUCl3tyv.png](https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-09-25%20at%202.27.32%20PM-ZWaUCl3tyv.png)

**non-PMA, dark: 0x707070**
![https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-09-25%20at%202.26.37%20PM-ncVkva9p2j.png](https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-09-25%20at%202.26.37%20PM-ncVkva9p2j.png)

**PMA, dark: 0x707070**
![https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-09-25%20at%202.28.00%20PM-hOqtVj6MH9.png](https://libgdx.badlogicgames.com/uploads/Screen%20Shot%202017-09-25%20at%202.28.00%20PM-hOqtVj6MH9.png)

**Comment by ivanpopelyshev** [comment] 2017-09-25 12:47
I'm making special texture for it.

**Comment by badlogic** [comment] 2017-09-25 12:51
Sorry, I was able to see the brokenness. My PMA code in the test was wrong :D

**Comment by ivanpopelyshev** [comment] 2017-09-25 12:52
We're making the texture for you anyway.

**Comment by badlogic** [comment] 2017-09-25 13:02
I can confirm non-PMA plus tint black broken (see screenshot comparison above), and your shader fixing it for non-PMA.

**Comment by badlogic** [comment] 2017-09-25 13:05
I've updated the test in the repo, lets you choose between old shader and new one. @NathanSweet non-PMA plus tint black was indeed broken, I suggest we update all tint black capable runtimes with Ivan's shader. The additional dark color alpha preparation is less expensive than setting a uniform for runtimes that already set dark color as a 32-bit packed rgba value, so I'd go with that.

**Comment by ivanpopelyshev** [comment] 2017-09-25 13:17
Did you think about using UNSIGNED_BYTE for those two vec4?

That's my shader in pixi plugin: https://github.com/gameofbombs/pixi-heaven/blob/master/src/twotint/sprites/SpriteHeavenRenderer.ts#L5 , https://github.com/gameofbombs/pixi-heaven/blob/master/src/twotint/ColorTransform.ts#L146

**Comment by badlogic** [comment] 2017-09-25 13:18
I did, but our meshes aren't setup to store packed data (yet).

**Comment by ivanpopelyshev** [comment] 2017-09-25 13:32
Well, I gave you the code, it has to be enough. I can create separate issue or PR for that thing.

**Comment by ivanpopelyshev** [comment] 2017-09-25 13:33
However its up to you whether to do it - it makes code less readable.

**Comment by ivanpopelyshev** [comment] 2017-09-25 13:46
Ok, that one has wrong line at the right side, but should be enough: 
![gray_alpha](https://user-images.githubusercontent.com/695831/30811495-0e04ef48-a211-11e7-896c-93040a86f720.png)

It has different alpha from left to right, and different colors from top to bottom.

**Comment by badlogic** [comment] 2017-09-25 13:54
Cool, thanks! We've decided to go with your math. I'm closing this issue in favor of the porting one here https://github.com/EsotericSoftware/spine-runtimes/issues/1003

**Closed as completed by badlogic** 2017-09-25 13:54 UTC
