### ISSUE TITLE
[csharp - 3.7] Case where PathConstraint does not place the bones correctly on the path

### ISSUE THREAD

**Issue by pharan** [EsotericSoftware/spine-runtimes#1222] opened 2018-12-07 15:09 UTC
The constrained bone chains on both the Tank and the Stretchyman skeletons are working correctly.

However, forum user reported: http://esotericsoftware.com/forum/Problem-upgrading-to-3-7-11175

Works fine in Spine editor.
Bones are misplaced in Unity.
![file](https://user-images.githubusercontent.com/1911082/49655060-7b80f780-fa74-11e8-8f88-87c28f79ace5.jpg)
Parts of the hair are weighted to a chain of bones constrained to paths.

In Unity, all the bones are placed at the center regardless of the value of `position` or `spacing`.
![image](https://user-images.githubusercontent.com/1911082/49655219-0b26a600-fa75-11e8-8d5b-170b1eefa058.png)

The PathConstraint settings are similar to Stretchyman's.
![image](https://user-images.githubusercontent.com/1911082/49699511-16acd500-fc0d-11e8-9eb1-420e99b9614b.png)

user's
![image](https://user-images.githubusercontent.com/1911082/49699489-e8c79080-fc0c-11e8-847f-9bf630acec0c.png)

But stretchyman's IK works correctly, while user's does not.

**Comment by pharan** [comment] 2018-12-09 15:56
![image](https://user-images.githubusercontent.com/1911082/49699593-0a754780-fc0e-11e8-8329-fca2dcf65717.png)

I've simplified the user's skeleton to have no other constraints except the ones for the hair.

The problem persists. But I think that rules it out as a constraint update order problem.

**Comment by HaraldCsaszar** [comment] 2018-12-13 09:17
Internal repro email hash for completeness:
FMfcgxvzLrQQMfNcTnRPJdcWKtDwQKlW

**Comment by HaraldCsaszar** [comment] 2018-12-15 15:52
Update order problem seems to be likely since changing order of reproduction asset path constraints from 3 and 4 to 2, hair is placed at desired origin.

**Comment by HaraldCsaszar** [comment] 2018-12-15 21:06
Fixed in spince-csharp, 3.7-beta branch.

**Closed as completed by HaraldCsaszar** 2018-12-15 21:06 UTC
