### ISSUE TITLE
[ts] skeleton.flipX does not work with PathConstraint.

### ISSUE THREAD

**Issue by ivanpopelyshev** [EsotericSoftware/spine-runtimes#737] opened 2016-10-19 15:38 UTC
In the end of the path position of bone is wrong. And flipY too. That's problem in pixi-spine runtime because flipY is true by default there ;)

I'm asking client if its ok to show their animation for you in private.

P.S. I remember that there were problems with flipX and IKConstraint too, gonna test it too.

**Comment by badlogic** [comment] 2016-10-19 16:02
That might be fixed in the spine-ts-3.5 branch. You'll need to export the model with Spine 3.5.03-beta if you want to give this a try.

**Comment by ivanpopelyshev** [comment] 2016-10-19 18:03
Yeah, and it broke all old exports, because transforms are working differently :(

**Comment by badlogic** [comment] 2016-10-20 12:51
I tested it with the latest dev branch and both flipX and flipY work as intended. Sorry for having to re-export.

**Comment by Skeptron** [comment] 2016-10-27 10:52
I'm having the same issue and I'm using IK Constraints

**Comment by ivanpopelyshev** [comment] 2016-10-27 11:39
@Skeptron can you please publish your example?

I had that code for pixi-spine before spine-ts convertion:

```js
if ((bone.worldSignX != bone.worldSignY) != (bone.skeleton.flipX != bone.skeleton.flipY)) rotation = 360 - rotation;
```

If we use it in the beginning of IKConstraint.apply, may be it'll be fixed?

**Comment by Skeptron** [comment] 2016-10-27 13:37
@ivanpopelyshev Thanks for the quick help, really appreciated!

Sorry I'm quite new to Spine-runtime, I'm using it for a Phaser project and the lack of native plugin had me use the spine-canvas runtime lib directly.

I'm also sorry I can't share code here for confidentiality issues (and even if I wanted to, the project is huge already, it wouldn't be that simple).

Where exactly did you insert that line? 

Here is the IkConstraint.apply() method in the file I'm using : https://github.com/EsotericSoftware/spine-runtimes/blob/master/spine-ts/build/spine-canvas.js#L1703

**Comment by ivanpopelyshev** [comment] 2016-10-27 13:50
@Skeptron near or instead of 

```ts
if (bone.scaleX < 0)
	rotationIK += 180;
```

But remember that I used it for previous transform model, not for latest. Also, there's no worldSignX, "bone.scaleX<0" should be used instead.

**Comment by badlogic** [comment] 2016-11-02 12:34
Another report of flipX not working as intended http://esotericsoftware.com/forum/flipping-an-animation-spine-js-runtime-7284

**Comment by Skeptron** [comment] 2016-11-02 17:05
When I read your post I tried again, and I managed to make it work : so first of all I'd like to apologise for wasting your time.

But still, it would work only if I set skeletonRenderer.triangleRendering = true, which is  quite strange to me (it is commented in the examples saying that it's related to mesh use). 

Whatever. Works like a charm now. Thanks a lot!

**Comment by badlogic** [comment] 2016-11-07 13:15
OK, thanks to @ivanpopelyshev we found out what's wrong, see latest commits on dev branch. Fixed in all runtimes! Thanks for reporting.

**Closed by badlogic** 2016-11-07 13:15 UTC
Labels: bug, runtimes

**Comment by ivanpopelyshev** [comment] 2016-11-07 13:17
Yay! gonna update pixi today )
