### ISSUE TITLE
[cocos2dx] BatchingExample crash in cocos2d-x v3.13

### ISSUE THREAD

**Issue by zloop1982** [EsotericSoftware/spine-runtimes#687] opened 2016-08-29 03:22 UTC
cocos2d-x version:3.13(branch v3)
devices test on: iphone 6plus  OS: ios 9.3.3
developing environments
Xcode version: 7.3.1 (7D1014)

Steps to Reproduce:

upgrade spine to newest (spine-c ,spine-cocos2dx)
try example in spine-cocos2dx.
will crash when you run BatchingExample or run RaptorExample and tap screen enter the batching scene.
xcode report :EXC_BAD_ACCESS in this line (function : fillVerticesAndIndices in CCRender)
memcpy(&_verts[_filledVertex], cmd->getVertices(), sizeof(V3F_C4B_T2F) * cmd->getVertexCount());

for memcpy to _verts is bad access.
_verts not null, _filledVertex less than 65536, in most of the time, _filledVertex is 512.
but it did not crashed in iOS simulator.

**Comment by zloop1982** [comment] 2016-08-29 18:03
my bad.
EXC_BAD_ACCESS is on cmd->getVertices(); not _verts.
getVertices() return _triangles.verts, address is 0x000000010783c810.

**Comment by zloop1982** [comment] 2016-08-29 19:22
finally, the crash is because for 50 spine boys , SkeletonBatch::setBufferSize(512)
is not enugh.
create 50 spine boys on device must use SkeletonBatch::setBufferSize(3600).
seems like the size of SkeletonBatch can not auto increase on iphone.

**Comment by zloop1982** [comment] 2016-08-30 05:49
I suggest to use malloc / free / realloc to manage the Batch buffer. 
Because V3F_C4B_T2F is just an pod struct.

The resize logic not work.

**Comment by badlogic** [comment] 2016-09-05 13:22
I can't reproduce this issue on iOS. Are you sure you have wired up everything correctly? Cocos2d-X still ships their own spine runtime. You have to remove it to use our official runtime.

**Comment by zloop1982** [comment] 2016-09-08 07:51
Ofcourse  I remove the old one. do you test on ios device?
you only can repro this in device, not on  iOS simulator.

**Comment by badlogic** [comment] 2016-09-11 11:36
This is now fixed. Please update to the latest spine-cocos2dx runtime and report back if the issue has not been fixed on your end.

**Closed by badlogic** 2016-09-11 11:36 UTC
Labels: bug, ready, runtimes
